### ISSUE TITLE
option --install-src-path not working

### ISSUE THREAD

**Issue by dr-ni** [rickysarraf/apt-offline#130]
"sudo apt-offline install --verbose bundle.zip --install-src-path /home/xy/" still creates a download folder at /tmp/ and nothing is written to /home/xy/
is this a bug?

**Comment by UNspawn-N4** [comment]
same problem for me

**Comment by rickysarraf** [comment]
Please when you file bug report, file a useful bug report. This bug report you filed has nothing I can make much out of, by looking at its content.

**Comment by rickysarraf** [comment]
```
rrs@priyasi:~$ apt-offline set -h
usage: apt-offline set [-h] [--verbose] [--simulate] [--install-packages [PKG [PKG ...]]]
                       [--install-src-packages [SOURCE PKG [SOURCE PKG ...]]] [--src-build-dep] [--release release_name] [--update] [--upgrade]
                       [--upgrade-type upgrade] [--generate-changelog] [--apt-backend apt-get]
                       apt-offline.sig

positional arguments:
  apt-offline.sig       Generate a signature file

optional arguments:
  -h, --help            show this help message and exit
  --verbose             Enable verbose messages
  --simulate            Just simulate. Very helpful when debugging
  --install-packages [PKG [PKG ...]]
                        Packages that need to be installed
  --install-src-packages [SOURCE PKG [SOURCE PKG ...]]
                        Source Packages that need to be installed
  --src-build-dep       Install Build Dependency packages for requested source packages
  --release release_name
                        Release target to install packages from
  --update              Generate Signature to update APT Database
  --upgrade             Generate Signature of packages to be upgraded
  --upgrade-type upgrade
                        Type of upgrade to do. Use one of upgrade, dist-upgrade, dselect-ugprade
  --generate-changelog  Generate changelog of the version to be downloaded
  --apt-backend apt-get
                        APT backend to use. One of: apt, apt-get, python-apt
21:00 ♒ ॐ ♅ ⛢  ☺ 😄    

rrs@priyasi:~$ apt-offline set /tmp/bash.src --install-src-packages bash --src-build-dep 
Gathering installation details for source package ['bash']
Generating Build-Dependency for source packages ['bash'].
21:00 ♒ ॐ ♅ ⛢  ☺ 😄    

rrs@priyasi:~$ cat /tmp/bash.src 
'http://deb.debian.org/debian/pool/main/b/bash/bash_5.0-7.dsc' bash_5.0-7.dsc 2296 SHA256:82a31f12b66a6e81036e84822767f730a4c918115b199433c7f30e9f7edf481f
'http://deb.debian.org/debian/pool/main/b/bash/bash_5.0.orig.tar.xz' bash_5.0.orig.tar.xz 5554808 SHA256:893858ba233d65bda38039e99dd96a4102b2f6a2d5e6c1c546e0794a60beed97
'http://deb.debian.org/debian/pool/main/b/bash/bash_5.0-7.debian.tar.xz' bash_5.0-7.debian.tar.xz 98836 SHA256:b669b5a6be08d1cb75a41bde3ea46862bfae73b3ed5045619cb4d340df2dfd01
'http://deb.debian.org/debian/pool/main/l/lmodern/fonts-lmodern_2.004.5-6_all.deb' fonts-lmodern_2.004.5-6_all.deb 4539292 MD5Sum:d2b6b6707523afeffc33bc7f90350698
'http://deb.debian.org/debian/pool/main/libt/libtext-unidecode-perl/libtext-unidecode-perl_1.30-1_all.deb' libtext-unidecode-perl_1.30-1_all.deb 103056 MD5Sum:3c602ce28ce0c279368398e0ec63850a
'http://deb.debian.org/debian/pool/main/s/sharutils/sharutils_4.15.2-5_amd64.deb' sharutils_1%3a4.15.2-5_amd64.deb 265532 MD5Sum:fafd55be268044b1cff8a60586411b90
'http://deb.debian.org/debian/pool/main/t/texi2html/texi2html_1.82+dfsg1-5_all.deb' texi2html_1.82+dfsg1-5_all.deb 355994 MD5Sum:ca8e888a5645da5092355cd706ce1456
'http://deb.debian.org/debian/pool/main/t/texinfo/texinfo_6.7.0.dfsg.2-5_amd64.deb' texinfo_6.7.0.dfsg.2-5_amd64.deb 1761316 MD5Sum:d425a880db24bde0a76518890dab941e
'http://deb.debian.org/debian/pool/main/t/texlive-base/texlive-fonts-recommended_2020.20200804-2_all.deb' texlive-fonts-recommended_2020.20200804-2_all.deb 5002604 MD5Sum:41f4f968e199f241ca988b1d495a33c9
'http://deb.debian.org/debian/pool/main/t/texlive-base/texlive-latex-base_2020.20200804-2_all.deb' texlive-latex-base_2020.20200804-2_all.deb 1066132 MD5Sum:fefe84f7a0a50a1b306f23cecb98a950
'http://deb.debian.org/debian/pool/main/t/time/time_1.7-25.1+b1_amd64.deb' time_1.7-25.1+b1_amd64.deb 31562 MD5Sum:ba55e0586d419472b3cdb557284a08c4
21:00 ♒ ॐ ♅ ⛢  ☺ 😄    



rrs@priyasi:~$ apt-offline get /tmp/bash.src --bundle /tmp/bash.zip

Fetching APT Data

Downloading http://deb.debian.org/debian/pool/main/b/bash/bash_5.0-7.dsc                                                             
http://deb.debian.org/debian/pool/main/b/bash/bash_5.0-7.dsc done                                                             
Downloading http://deb.debian.org/debian/pool/main/b/bash/bash_5.0.orig.tar.xz                                                             
http://deb.debian.org/debian/pool/main/b/bash/bash_5.0.orig.tar.xz done                                                             
Downloading http://deb.debian.org/debian/pool/main/b/bash/bash_5.0-7.debian.tar.xz                                                             
http://deb.debian.org/debian/pool/main/b/bash/bash_5.0-7.debian.tar.xz done                                                             
Downloading fonts-lmodern - 4 MiB                                                             
fonts-lmodern done                                                             
Downloading libtext-unidecode-perl - 100 KiB                                                             
libtext-unidecode-perl done                                                             
Downloading sharutils - 259 KiB                                                             
sharutils done                                                             
Downloading texi2html - 347 KiB                                                             
texi2html done                                                             
Downloading texinfo - 1 MiB                                                             
texinfo done                                                             
Downloading texlive-fonts-recommended - 4 MiB                                                             
texlive-fonts-recommended done                                                             
Downloading texlive-latex-base - 1 MiB                                                             
texlive-latex-base done                                                             
Downloading time - 30 KiB                                                             
time done                                                             
 11 /  11 items: [##############################] 100.0% of 17 MiB
Downloaded data to /tmp/bash.zip
21:02 ♒ ॐ ♅ ⛢  ☺ 😄    



rrs@priyasi:~$ apt-offline install -h
usage: apt-offline install [-h] [--verbose] [--simulate] [--install-src-path INSTALL_SRC_PATH] [--skip-bug-reports] [--skip-changelog]
                           [--allow-unauthenticated] [--strict-deb-check]
                           apt-offline-download.zip | apt-offline-download/

positional arguments:
  apt-offline-download.zip | apt-offline-download/
                        Install apt-offline data, a bundle file or a directory

optional arguments:
  -h, --help            show this help message and exit
  --verbose             Enable verbose messages
  --simulate            Just simulate. Very helpful when debugging
  --install-src-path INSTALL_SRC_PATH
                        Install src packages to specified path.
  --skip-bug-reports    Skip the bug report check
  --skip-changelog      Skip display of changelog
  --allow-unauthenticated
                        Ignore apt gpg signatures mismatch
  --strict-deb-check    Perform strict checksum validaton for downloaded .deb files
21:02 ♒ ॐ ♅ ⛢  ☺ 😄    


rrs@priyasi:~$ apt-offline install /tmp/bash.zip --install-src-path /var/tmp/bash-foo
ERROR: Couldn't open lockfile
ERROR: Not a folder.
Traceback (most recent call last):
  File "/usr/bin/apt-offline", line 28, in <module>
    main()
  File "/usr/lib/python3/dist-packages/apt_offline_core/AptOfflineCoreLib.py", line 2379, in main
    args.func(args)
  File "/usr/lib/python3/dist-packages/apt_offline_core/AptOfflineCoreLib.py", line 1878, in installer
    InstallerInstance = InstallerClass(args)
TypeError: __init__() should return None, not 'bool'
21:03 ♒ ॐ ♅ ⛢   ☹ 😟=> 1  


rrs@priyasi:~$ mkdir /var/tmp/bash
21:03 ♒ ॐ ♅ ⛢  ☺ 😄    


rrs@priyasi:~$ sudo apt-offline install /tmp/bash.zip --install-src-path /var/tmp/bash
Traceback (most recent call last):
  File "/usr/bin/apt-offline", line 28, in <module>
    main()
  File "/usr/lib/python3/dist-packages/apt_offline_core/AptOfflineCoreLib.py", line 2379, in main
    args.func(args)
  File "/usr/lib/python3/dist-packages/apt_offline_core/AptOfflineCoreLib.py", line 1906, in installer
    if SrcPkgIdentifier.startswith('Files:'):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
21:03 ♒ ॐ ♅ ⛢   ☹ 😟=> 1  



rrs@priyasi:~/.../apt-offline (master)$ sudo ./apt-offline --verbose install /tmp/bash.zip --install-src-path /var/tmp/bash
Proceeding with installation
Installing src package file bash_5.0-7.dsc to /var/tmp/bash.
Installing src package file bash_5.0.orig.tar.xz to /var/tmp/bash.
Installing src package file bash_5.0-7.debian.tar.xz to /var/tmp/bash.
fonts-lmodern_2.004.5-6_all.deb file synced.
libtext-unidecode-perl_1.30-1_all.deb file synced.
sharutils_1%3a4.15.2-5_amd64.deb file synced.
texi2html_1.82+dfsg1-5_all.deb file synced.
texinfo_6.7.0.dfsg.2-5_amd64.deb file synced.
texlive-fonts-recommended_2020.20200804-2_all.deb file synced.
texlive-latex-base_2020.20200804-2_all.deb file synced.
time_1.7-25.1+b1_amd64.deb file synced.
21:32 ♒ ॐ ♅ ⛢  ☺ 😄    


rrs@priyasi:~/.../apt-offline (master)$ ls /var/tmp/bash/
bash_5.0-7.debian.tar.xz  bash_5.0-7.dsc  bash_5.0.orig.tar.xz
21:33 ♒ ॐ ♅ ⛢  ☺ 😄    


rrs@priyasi:~/.../apt-offline (master)$ git diff
diff --git a/apt_offline_core/AptOfflineCoreLib.py b/apt_offline_core/AptOfflineCoreLib.py
index b385748..8c898b4 100644
--- a/apt_offline_core/AptOfflineCoreLib.py
+++ b/apt_offline_core/AptOfflineCoreLib.py
@@ -1917,12 +1917,13 @@ def installer( args ):
             if filename.endswith(".dsc"):
                 SrcPkgName = filename.split('_')[0]
                 temp = tempfile.NamedTemporaryFile()
-                temp.file.write( zipBugFile.read( filename ) )
+                temp.file.write(zipBugFile.read(filename))
                 temp.file.flush()
                 temp.file.seek( 0 ) #Let's go back to the start of the file
                 SrcPkgDict[SrcPkgName] = []
                 marker = None
                 for SrcPkgIdentifier in temp.file.readlines():
+                    SrcPkgIdentifier = SrcPkgIdentifier.decode('utf-8')
                     if SrcPkgIdentifier.startswith('Files:'):
                         marker = True
                         continue
21:33 ♒ ॐ ♅ ⛢  ☺ 😄    
```

**Comment by dr-ni** [comment]
i've just cloned the new version, still same behaviour:

sudo apt-offline install --verbose /var/www/html/backup/2020092419h03-00000000a7651246.sysup --install-src-path /home/pi/tmp/

VERBOSE: Namespace(allow_unauthenticated=False, func=<function installer at 0xb5f38348>, install='/var/www/html/backup/2020092419h03-00000000a7651246.sysup', install_simulate=False, install_src_path='/home/pi/tmp/', skip_bug_reports=False, skip_changelog=False, strict_deb_check=False, verbose=True)
VERBOSE: No changelog available
Proceeding with installation
VERBOSE: {}
VERBOSE: Great!!! No bugs found for all the packages that were downloaded.

VERBOSE: APT Signature verification path is: ['/etc/apt/trusted.gpg.d/', '/etc/apt/trusted.gpg']
VERBOSE: /tmp/tmpc9wzr3ze/archive.raspberrypi.org_debian_dists_stretch_Release.gpg
VERBOSE: Command is: ['/usr/bin/gpgv', '--ignore-time-conflict', '--keyring', '/etc/apt/trusted.gpg', '/tmp/tmpc9wzr3ze/archive.raspberrypi.org_debian_dists_stretch_Release.gpg', '/tmp/tmpc9wzr3ze/archive.raspberrypi.org_debian_dists_stretch_Release']
VERBOSE: /tmp/tmpc9wzr3ze/archive.raspberrypi.org_debian_dists_stretch_Release is gpg clean
VERBOSE: This error should be ignoredVERBOSE: /tmp/tmpc9wzr3ze/raspbian.raspberrypi.org_raspbian_dists_stretch_Release.gpg
VERBOSE: Command is: ['/usr/bin/gpgv', '--ignore-time-conflict', '--keyring', '/etc/apt/trusted.gpg', '/tmp/tmpc9wzr3ze/raspbian.raspberrypi.org_raspbian_dists_stretch_Release.gpg', '/tmp/tmpc9wzr3ze/raspbian.raspberrypi.org_raspbian_dists_stretch_Release']
VERBOSE: /tmp/tmpc9wzr3ze/raspbian.raspberrypi.org_raspbian_dists_stretch_Release is gpg clean
VERBOSE: This error should be ignoredVERBOSE: localFile /tmp/tmpc9wzr3ze/archive.raspberrypi.org_debian_dists_stretch_main_binary-armhf_Packages.gz Integrity with checksum 1d8dfa9db9c063a9e5b784fa91d8269e201c6bd29c0347af9ac49576552f480e matches
VERBOSE: localFile /tmp/tmpc9wzr3ze/archive.raspberrypi.org_debian_dists_stretch_ui_binary-armhf_Packages.gz Integrity with checksum 4ba37435fa46bbf93ecfb8666bd438cfa51ce1b8a36141d432c0e3dfd34f6fdc matches
VERBOSE: localFile /tmp/tmpc9wzr3ze/raspbian.raspberrypi.org_raspbian_dists_stretch_contrib_binary-armhf_Packages.xz Integrity with checksum 1a2d1cebd7cbf3df8b750e2167b132564e53c7df5e007a4bdc43486a1828a5ea matches
VERBOSE: localFile /tmp/tmpc9wzr3ze/raspbian.raspberrypi.org_raspbian_dists_stretch_main_binary-armhf_Packages.xz Integrity with checksum b9b589fb0920591fc1f98a74ff11b2f3a8227f0b235208a12793ada509007370 matches
VERBOSE: localFile /tmp/tmpc9wzr3ze/raspbian.raspberrypi.org_raspbian_dists_stretch_non-free_binary-armhf_Packages.xz Integrity with checksum df67dee7e143b8e78583ba5b38535e16fad7c24ac3f69d08ea232dc48d73183e matches
VERBOSE: localFile /tmp/tmpc9wzr3ze/raspbian.raspberrypi.org_raspbian_dists_stretch_rpi_binary-armhf_Packages.xz Integrity with checksum bec65b0eb62d0a946b4a7848edf49e2b4b707cb4f37e6f0344473d53d6bfc3eb matches
VERBOSE: File is archive.raspberrypi.org_debian_dists_stretch_Release.gpg, hence 'True'.
VERBOSE: archive.raspberrypi.org_debian_dists_stretch_Release.gpg file synced to APT.
archive.raspberrypi.org_debian_dists_stretch_Release.gpg synced.
VERBOSE: archive.raspberrypi.org_debian_dists_stretch_Release file synced to APT.
archive.raspberrypi.org_debian_dists_stretch_Release synced.
VERBOSE: File is raspbian.raspberrypi.org_raspbian_dists_stretch_Release.gpg, hence 'True'.
VERBOSE: raspbian.raspberrypi.org_raspbian_dists_stretch_Release.gpg file synced to APT.
raspbian.raspberrypi.org_raspbian_dists_stretch_Release.gpg synced.
VERBOSE: raspbian.raspberrypi.org_raspbian_dists_stretch_Release file synced to APT.
raspbian.raspberrypi.org_raspbian_dists_stretch_Release synced.
VERBOSE: Synchronized file to /var/lib/apt/lists/archive.raspberrypi.org_debian_dists_stretch_main_binary-armhf_Packages
VERBOSE: /var/lib/apt/lists/archive.raspberrypi.org_debian_dists_stretch_main_binary-armhf_Packages file synced to APT.
archive.raspberrypi.org_debian_dists_stretch_main_binary-armhf_Packages.gz synced.
VERBOSE: Synchronized file to /var/lib/apt/lists/archive.raspberrypi.org_debian_dists_stretch_ui_binary-armhf_Packages
VERBOSE: /var/lib/apt/lists/archive.raspberrypi.org_debian_dists_stretch_ui_binary-armhf_Packages file synced to APT.
archive.raspberrypi.org_debian_dists_stretch_ui_binary-armhf_Packages.gz synced.
VERBOSE: Synchronized file to /var/lib/apt/lists/raspbian.raspberrypi.org_raspbian_dists_stretch_contrib_binary-armhf_Packages
VERBOSE: /var/lib/apt/lists/raspbian.raspberrypi.org_raspbian_dists_stretch_contrib_binary-armhf_Packages file synced to APT.
raspbian.raspberrypi.org_raspbian_dists_stretch_contrib_binary-armhf_Packages.xz synced.
VERBOSE: Synchronized file to /var/lib/apt/lists/raspbian.raspberrypi.org_raspbian_dists_stretch_main_binary-armhf_Packages
VERBOSE: /var/lib/apt/lists/raspbian.raspberrypi.org_raspbian_dists_stretch_main_binary-armhf_Packages file synced to APT.
raspbian.raspberrypi.org_raspbian_dists_stretch_main_binary-armhf_Packages.xz synced.
VERBOSE: Synchronized file to /var/lib/apt/lists/raspbian.raspberrypi.org_raspbian_dists_stretch_non-free_binary-armhf_Packages
VERBOSE: /var/lib/apt/lists/raspbian.raspberrypi.org_raspbian_dists_stretch_non-free_binary-armhf_Packages file synced to APT.
raspbian.raspberrypi.org_raspbian_dists_stretch_non-free_binary-armhf_Packages.xz synced.
VERBOSE: Synchronized file to /var/lib/apt/lists/raspbian.raspberrypi.org_raspbian_dists_stretch_rpi_binary-armhf_Packages
VERBOSE: /var/lib/apt/lists/raspbian.raspberrypi.org_raspbian_dists_stretch_rpi_binary-armhf_Packages file synced to APT.
raspbian.raspberrypi.org_raspbian_dists_stretch_rpi_binary-armhf_Packages.xz synced.


=>>>  still a folder tmpc9wzr3ze is made in /tmp/

pi@pi:~/apt-offline$ sudo ls /tmp/tmpc9wzr3ze/
archive.raspberrypi.org_debian_dists_stretch_InRelease
archive.raspberrypi.org_debian_dists_stretch_main_binary-armhf_Packages.gz
archive.raspberrypi.org_debian_dists_stretch_Release
archive.raspberrypi.org_debian_dists_stretch_Release.gpg
archive.raspberrypi.org_debian_dists_stretch_ui_binary-armhf_Packages.gz
raspbian.raspberrypi.org_raspbian_dists_stretch_contrib_binary-armhf_Packages.xz
raspbian.raspberrypi.org_raspbian_dists_stretch_InRelease
raspbian.raspberrypi.org_raspbian_dists_stretch_main_binary-armhf_Packages.xz
raspbian.raspberrypi.org_raspbian_dists_stretch_non-free_binary-armhf_Packages.xz
raspbian.raspberrypi.org_raspbian_dists_stretch_Release
raspbian.raspberrypi.org_raspbian_dists_stretch_Release.gpg
raspbian.raspberrypi.org_raspbian_dists_stretch_rpi_binary-armhf_Packages.xz
pi@pi:~/apt-offline

my /tmp/ is only a small ramdisk so I need another location for this folder
is'nt this possible by changing the --install-src-path?

**Comment by rickysarraf** [comment]
> my /tmp/ is only a small ramdisk so I need another location for this folder
> is'nt this possible by changing the --install-src-path?

Yes. We heavily make use of a temporary directory. Because, otherwise, users will have to unzip the downloaded archive file, which would be more cumbersome and error prone. 

What that temporary directory is is left to respective operating systems.
For corner cases like your's, where you have a limited /tmp/, your best option is to override the os provided temporary directory. So in this case, it'd be `$TMPDIR`. Just set it to a disk location with enough space and it should work.


And if it works, please do report back here.

**Comment by rickysarraf** [comment]
Oh!! And you've mis-understood the `--install-src-path` opiton. It is completely unrelated to the use case you have.

**Comment by dr-ni** [comment]
changing $TMPDIR does not solve the problem for my case. /tmp is mounted as ramdisk for regular repeated disk interactions to reduce sd-card write cycles. Too many write cycles will reduce sd-card life time. If $TMPDIR is pointing again to sd-card I don't need a ramdisk at all.
Is it possible to introduce another option "--tempdir" ?
This would solve all problems.
... would make me very happy :-)

**Comment by rickysarraf** [comment]
> changing $TMPDIR does not solve the problem for my case. /tmp is mounted as ramdisk for regular repeated disk interactions to reduce sd-card write cycles. Too many write cycles will reduce sd-card life time. If $TMPDIR is pointing again to sd-card I don't need a ramdisk at all.
> Is it possible to introduce another option "--tempdir" ?
> This would solve all problems.
> ... would make me very happy :-)

But how will an option solve the problem ? You'll still have to point it to a path, which you say you do not want to provide given it is an SDCARD.

**Comment by dr-ni** [comment]
There are two cases:

1) regular repeated write cycles by system applications using $TMPDIR which should use a ramdisk

2) unregulare rare cases which need much disk space like apt-offline using the temp on sdcard
