### ISSUE TITLE
GUI Did Not Start

### ISSUE THREAD

**Issue by KitchM** [rickysarraf/apt-offline#132]
I typed in apt-offline-gui and got:
Traceback (most recent call last):
  File "/usr/local/bin/apt-offline-gui", line 28, in <module>
    from apt_offline_gui.AptOfflineQtMain import AptOfflineQtMain
  File "/usr/local/lib/python3.7/dist-packages/apt_offline_gui/AptOfflineQtMain.py", line 4, in <module>
    from apt_offline_gui.Ui_AptOfflineQtMain import Ui_AptOfflineMain
ModuleNotFoundError: No module named 'apt_offline_gui.Ui_AptOfflineQtMain'

**Comment by rickysarraf** [comment]
How did you install it ? Can you give me the exact steps you ran to install it ? Preferably, share the full console output.

**Comment by KitchM** [comment]
I tried to follow the instructions you give:
##  Under Linux

# Pre-requisites
Please refer to requirements.txt for dependencies that need to be pre-installed for apt-offline. Note: If using a package from your distribution, manual installation of dependencies should not be required

Let me note here that the Debian 10 I use does not have a package of yours.  So I read:
# Incase users use it directly from source, please ensure following modules
# are installed
argparse
magic
soappy
lzma

sudo apt install argparse
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package argparse

sudo apt install magic
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Suggested packages:
  irsim
The following NEW packages will be installed:
  magic
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 1,587 kB of archives.
After this operation, 5,018 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian buster/main amd64 magic amd64 8.1.223+ds.1-1 [1,587 kB]
Fetched 1,587 kB in 2s (650 kB/s)
Selecting previously unselected package magic.
(Reading database ... 230947 files and directories currently installed.)
Preparing to unpack .../magic_8.1.223+ds.1-1_amd64.deb ...
Unpacking magic (8.1.223+ds.1-1) ...
Setting up magic (8.1.223+ds.1-1) ...
Processing triggers for man-db (2.8.5-2) ...
Processing triggers for menu (2.1.47+b1) ...

sudo apt install soappy
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package soappy

sudo apt install lzma
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  lzma
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 48.1 kB of archives.
After this operation, 144 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian buster/main amd64 lzma amd64 9.22-2.1 [48.1 kB]
Fetched 48.1 kB in 0s (254 kB/s)
Selecting previously unselected package lzma.
(Reading database ... 231332 files and directories currently installed.)
Preparing to unpack .../lzma_9.22-2.1_amd64.deb ...
Unpacking lzma (9.22-2.1) ...
Setting up lzma (9.22-2.1) ...
update-alternatives: using /usr/bin/lzmp to provide /usr/bin/lzma (lzma) in auto mode
Processing triggers for man-db (2.8.5-2) ...

cd Downloads/apt-offline-1.8.2

# To build
make build

cd apt_offline_gui ; ./genui.sh || exit 1
Compiling Ui files
Compiling file AptOfflineQtAbout.ui into Ui_AptOfflineQtAbout.py
./genui.sh: 12: ./genui.sh: pyuic5: not found
Compiling file AptOfflineQtCreateProfile.ui into Ui_AptOfflineQtCreateProfile.py
./genui.sh: 12: ./genui.sh: pyuic5: not found
Compiling file AptOfflineQtFetch.ui into Ui_AptOfflineQtFetch.py
./genui.sh: 12: ./genui.sh: pyuic5: not found
Compiling file AptOfflineQtFetchOptions.ui into Ui_AptOfflineQtFetchOptions.py
./genui.sh: 12: ./genui.sh: pyuic5: not found
Compiling file AptOfflineQtInstall.ui into Ui_AptOfflineQtInstall.py
./genui.sh: 12: ./genui.sh: pyuic5: not found
Compiling file AptOfflineQtInstallBugList.ui into Ui_AptOfflineQtInstallBugList.py
./genui.sh: 12: ./genui.sh: pyuic5: not found
Compiling file AptOfflineQtInstallChangelog.ui into Ui_AptOfflineQtInstallChangelog.py
./genui.sh: 12: ./genui.sh: pyuic5: not found
Compiling file AptOfflineQtMain.ui into Ui_AptOfflineQtMain.py
./genui.sh: 12: ./genui.sh: pyuic5: not found
Compiling file AptOfflineQtSaveZip.ui into Ui_AptOfflineQtSaveZip.py
./genui.sh: 12: ./genui.sh: pyuic5: not found
Compiling Resources files
./genui.sh: 16: ./genui.sh: pyrcc5: not found
Done
python3 setup.py build
running build
running build_py
file apt_offline_gui/resources_rc.py (for module apt_offline_gui.resources_rc) not found
file apt_offline_gui/Ui_AptOfflineQtAbout.py (for module apt_offline_gui.Ui_AptOfflineQtAbout) not found
file apt_offline_gui/Ui_AptOfflineQtCreateProfile.py (for module apt_offline_gui.Ui_AptOfflineQtCreateProfile) not found
file apt_offline_gui/Ui_AptOfflineQtFetch.py (for module apt_offline_gui.Ui_AptOfflineQtFetch) not found
file apt_offline_gui/Ui_AptOfflineQtFetchOptions.py (for module apt_offline_gui.Ui_AptOfflineQtFetchOptions) not found
file apt_offline_gui/Ui_AptOfflineQtInstall.py (for module apt_offline_gui.Ui_AptOfflineQtInstall) not found
file apt_offline_gui/Ui_AptOfflineQtInstallBugList.py (for module apt_offline_gui.Ui_AptOfflineQtInstallBugList) not found
file apt_offline_gui/Ui_AptOfflineQtInstallChangelog.py (for module apt_offline_gui.Ui_AptOfflineQtInstallChangelog) not found
file apt_offline_gui/Ui_AptOfflineQtMain.py (for module apt_offline_gui.Ui_AptOfflineQtMain) not found
file apt_offline_gui/Ui_AptOfflineQtSaveZip.py (for module apt_offline_gui.Ui_AptOfflineQtSaveZip) not found
file apt_offline_gui/resources_rc.py (for module apt_offline_gui.resources_rc) not found
file apt_offline_gui/Ui_AptOfflineQtAbout.py (for module apt_offline_gui.Ui_AptOfflineQtAbout) not found
file apt_offline_gui/Ui_AptOfflineQtCreateProfile.py (for module apt_offline_gui.Ui_AptOfflineQtCreateProfile) not found
file apt_offline_gui/Ui_AptOfflineQtFetch.py (for module apt_offline_gui.Ui_AptOfflineQtFetch) not found
file apt_offline_gui/Ui_AptOfflineQtFetchOptions.py (for module apt_offline_gui.Ui_AptOfflineQtFetchOptions) not found
file apt_offline_gui/Ui_AptOfflineQtInstall.py (for module apt_offline_gui.Ui_AptOfflineQtInstall) not found
file apt_offline_gui/Ui_AptOfflineQtInstallBugList.py (for module apt_offline_gui.Ui_AptOfflineQtInstallBugList) not found
file apt_offline_gui/Ui_AptOfflineQtInstallChangelog.py (for module apt_offline_gui.Ui_AptOfflineQtInstallChangelog) not found
file apt_offline_gui/Ui_AptOfflineQtMain.py (for module apt_offline_gui.Ui_AptOfflineQtMain) not found
file apt_offline_gui/Ui_AptOfflineQtSaveZip.py (for module apt_offline_gui.Ui_AptOfflineQtSaveZip) not found
running build_scripts

# To Install (You might need to be root)
make install

python3 setup.py install
running install
running build
running build_py
file apt_offline_gui/resources_rc.py (for module apt_offline_gui.resources_rc) not found
file apt_offline_gui/Ui_AptOfflineQtAbout.py (for module apt_offline_gui.Ui_AptOfflineQtAbout) not found
file apt_offline_gui/Ui_AptOfflineQtCreateProfile.py (for module apt_offline_gui.Ui_AptOfflineQtCreateProfile) not found
file apt_offline_gui/Ui_AptOfflineQtFetch.py (for module apt_offline_gui.Ui_AptOfflineQtFetch) not found
file apt_offline_gui/Ui_AptOfflineQtFetchOptions.py (for module apt_offline_gui.Ui_AptOfflineQtFetchOptions) not found
file apt_offline_gui/Ui_AptOfflineQtInstall.py (for module apt_offline_gui.Ui_AptOfflineQtInstall) not found
file apt_offline_gui/Ui_AptOfflineQtInstallBugList.py (for module apt_offline_gui.Ui_AptOfflineQtInstallBugList) not found
file apt_offline_gui/Ui_AptOfflineQtInstallChangelog.py (for module apt_offline_gui.Ui_AptOfflineQtInstallChangelog) not found
file apt_offline_gui/Ui_AptOfflineQtMain.py (for module apt_offline_gui.Ui_AptOfflineQtMain) not found
file apt_offline_gui/Ui_AptOfflineQtSaveZip.py (for module apt_offline_gui.Ui_AptOfflineQtSaveZip) not found
file apt_offline_gui/resources_rc.py (for module apt_offline_gui.resources_rc) not found
file apt_offline_gui/Ui_AptOfflineQtAbout.py (for module apt_offline_gui.Ui_AptOfflineQtAbout) not found
file apt_offline_gui/Ui_AptOfflineQtCreateProfile.py (for module apt_offline_gui.Ui_AptOfflineQtCreateProfile) not found
file apt_offline_gui/Ui_AptOfflineQtFetch.py (for module apt_offline_gui.Ui_AptOfflineQtFetch) not found
file apt_offline_gui/Ui_AptOfflineQtFetchOptions.py (for module apt_offline_gui.Ui_AptOfflineQtFetchOptions) not found
file apt_offline_gui/Ui_AptOfflineQtInstall.py (for module apt_offline_gui.Ui_AptOfflineQtInstall) not found
file apt_offline_gui/Ui_AptOfflineQtInstallBugList.py (for module apt_offline_gui.Ui_AptOfflineQtInstallBugList) not found
file apt_offline_gui/Ui_AptOfflineQtInstallChangelog.py (for module apt_offline_gui.Ui_AptOfflineQtInstallChangelog) not found
file apt_offline_gui/Ui_AptOfflineQtMain.py (for module apt_offline_gui.Ui_AptOfflineQtMain) not found
file apt_offline_gui/Ui_AptOfflineQtSaveZip.py (for module apt_offline_gui.Ui_AptOfflineQtSaveZip) not found
running build_scripts
running install_lib
running install_scripts
changing mode of /usr/local/bin/apt-offline to 755
error: [Errno 1] Operation not permitted: '/usr/local/bin/apt-offline'
make: *** [Makefile:10: install] Error 1

apt-offline-gui
Traceback (most recent call last):
  File "/usr/local/bin/apt-offline-gui", line 28, in <module>
    from apt_offline_gui.AptOfflineQtMain import AptOfflineQtMain
  File "/usr/local/lib/python3.7/dist-packages/apt_offline_gui/AptOfflineQtMain.py", line 4, in <module>
    from apt_offline_gui.Ui_AptOfflineQtMain import Ui_AptOfflineMain
ModuleNotFoundError: No module named 'apt_offline_gui.Ui_AptOfflineQtMain'



## Under Microsoft Windows

# Execute the file using the python interpreter
# Assuming python.exe is in your path

#TODO: Find a windows native way to update/generate the Ui files
# The equivalent of genui.sh

# To build
C:\> python3 setup.py build

# To install
C:\> python3 setup.py install

**Comment by KitchM** [comment]
Then I tried as root:
make build
cd apt_offline_gui ; ./genui.sh || exit 1
Compiling Ui files
Compiling file AptOfflineQtAbout.ui into Ui_AptOfflineQtAbout.py
./genui.sh: 12: ./genui.sh: pyuic5: not found
Compiling file AptOfflineQtCreateProfile.ui into Ui_AptOfflineQtCreateProfile.py
./genui.sh: 12: ./genui.sh: pyuic5: not found
Compiling file AptOfflineQtFetch.ui into Ui_AptOfflineQtFetch.py
./genui.sh: 12: ./genui.sh: pyuic5: not found
Compiling file AptOfflineQtFetchOptions.ui into Ui_AptOfflineQtFetchOptions.py
./genui.sh: 12: ./genui.sh: pyuic5: not found
Compiling file AptOfflineQtInstall.ui into Ui_AptOfflineQtInstall.py
./genui.sh: 12: ./genui.sh: pyuic5: not found
Compiling file AptOfflineQtInstallBugList.ui into Ui_AptOfflineQtInstallBugList.py
./genui.sh: 12: ./genui.sh: pyuic5: not found
Compiling file AptOfflineQtInstallChangelog.ui into Ui_AptOfflineQtInstallChangelog.py
./genui.sh: 12: ./genui.sh: pyuic5: not found
Compiling file AptOfflineQtMain.ui into Ui_AptOfflineQtMain.py
./genui.sh: 12: ./genui.sh: pyuic5: not found
Compiling file AptOfflineQtSaveZip.ui into Ui_AptOfflineQtSaveZip.py
./genui.sh: 12: ./genui.sh: pyuic5: not found
Compiling Resources files
./genui.sh: 16: ./genui.sh: pyrcc5: not found
Done
python3 setup.py build
running build
running build_py
file apt_offline_gui/resources_rc.py (for module apt_offline_gui.resources_rc) not found
file apt_offline_gui/Ui_AptOfflineQtAbout.py (for module apt_offline_gui.Ui_AptOfflineQtAbout) not found
file apt_offline_gui/Ui_AptOfflineQtCreateProfile.py (for module apt_offline_gui.Ui_AptOfflineQtCreateProfile) not found
file apt_offline_gui/Ui_AptOfflineQtFetch.py (for module apt_offline_gui.Ui_AptOfflineQtFetch) not found
file apt_offline_gui/Ui_AptOfflineQtFetchOptions.py (for module apt_offline_gui.Ui_AptOfflineQtFetchOptions) not found
file apt_offline_gui/Ui_AptOfflineQtInstall.py (for module apt_offline_gui.Ui_AptOfflineQtInstall) not found
file apt_offline_gui/Ui_AptOfflineQtInstallBugList.py (for module apt_offline_gui.Ui_AptOfflineQtInstallBugList) not found
file apt_offline_gui/Ui_AptOfflineQtInstallChangelog.py (for module apt_offline_gui.Ui_AptOfflineQtInstallChangelog) not found
file apt_offline_gui/Ui_AptOfflineQtMain.py (for module apt_offline_gui.Ui_AptOfflineQtMain) not found
file apt_offline_gui/Ui_AptOfflineQtSaveZip.py (for module apt_offline_gui.Ui_AptOfflineQtSaveZip) not found
file apt_offline_gui/resources_rc.py (for module apt_offline_gui.resources_rc) not found
file apt_offline_gui/Ui_AptOfflineQtAbout.py (for module apt_offline_gui.Ui_AptOfflineQtAbout) not found
file apt_offline_gui/Ui_AptOfflineQtCreateProfile.py (for module apt_offline_gui.Ui_AptOfflineQtCreateProfile) not found
file apt_offline_gui/Ui_AptOfflineQtFetch.py (for module apt_offline_gui.Ui_AptOfflineQtFetch) not found
file apt_offline_gui/Ui_AptOfflineQtFetchOptions.py (for module apt_offline_gui.Ui_AptOfflineQtFetchOptions) not found
file apt_offline_gui/Ui_AptOfflineQtInstall.py (for module apt_offline_gui.Ui_AptOfflineQtInstall) not found
file apt_offline_gui/Ui_AptOfflineQtInstallBugList.py (for module apt_offline_gui.Ui_AptOfflineQtInstallBugList) not found
file apt_offline_gui/Ui_AptOfflineQtInstallChangelog.py (for module apt_offline_gui.Ui_AptOfflineQtInstallChangelog) not found
file apt_offline_gui/Ui_AptOfflineQtMain.py (for module apt_offline_gui.Ui_AptOfflineQtMain) not found
file apt_offline_gui/Ui_AptOfflineQtSaveZip.py (for module apt_offline_gui.Ui_AptOfflineQtSaveZip) not found
running build_scripts

make install
python3 setup.py install
running install
running build
running build_py
file apt_offline_gui/resources_rc.py (for module apt_offline_gui.resources_rc) not found
file apt_offline_gui/Ui_AptOfflineQtAbout.py (for module apt_offline_gui.Ui_AptOfflineQtAbout) not found
file apt_offline_gui/Ui_AptOfflineQtCreateProfile.py (for module apt_offline_gui.Ui_AptOfflineQtCreateProfile) not found
file apt_offline_gui/Ui_AptOfflineQtFetch.py (for module apt_offline_gui.Ui_AptOfflineQtFetch) not found
file apt_offline_gui/Ui_AptOfflineQtFetchOptions.py (for module apt_offline_gui.Ui_AptOfflineQtFetchOptions) not found
file apt_offline_gui/Ui_AptOfflineQtInstall.py (for module apt_offline_gui.Ui_AptOfflineQtInstall) not found
file apt_offline_gui/Ui_AptOfflineQtInstallBugList.py (for module apt_offline_gui.Ui_AptOfflineQtInstallBugList) not found
file apt_offline_gui/Ui_AptOfflineQtInstallChangelog.py (for module apt_offline_gui.Ui_AptOfflineQtInstallChangelog) not found
file apt_offline_gui/Ui_AptOfflineQtMain.py (for module apt_offline_gui.Ui_AptOfflineQtMain) not found
file apt_offline_gui/Ui_AptOfflineQtSaveZip.py (for module apt_offline_gui.Ui_AptOfflineQtSaveZip) not found
file apt_offline_gui/resources_rc.py (for module apt_offline_gui.resources_rc) not found
file apt_offline_gui/Ui_AptOfflineQtAbout.py (for module apt_offline_gui.Ui_AptOfflineQtAbout) not found
file apt_offline_gui/Ui_AptOfflineQtCreateProfile.py (for module apt_offline_gui.Ui_AptOfflineQtCreateProfile) not found
file apt_offline_gui/Ui_AptOfflineQtFetch.py (for module apt_offline_gui.Ui_AptOfflineQtFetch) not found
file apt_offline_gui/Ui_AptOfflineQtFetchOptions.py (for module apt_offline_gui.Ui_AptOfflineQtFetchOptions) not found
file apt_offline_gui/Ui_AptOfflineQtInstall.py (for module apt_offline_gui.Ui_AptOfflineQtInstall) not found
file apt_offline_gui/Ui_AptOfflineQtInstallBugList.py (for module apt_offline_gui.Ui_AptOfflineQtInstallBugList) not found
file apt_offline_gui/Ui_AptOfflineQtInstallChangelog.py (for module apt_offline_gui.Ui_AptOfflineQtInstallChangelog) not found
file apt_offline_gui/Ui_AptOfflineQtMain.py (for module apt_offline_gui.Ui_AptOfflineQtMain) not found
file apt_offline_gui/Ui_AptOfflineQtSaveZip.py (for module apt_offline_gui.Ui_AptOfflineQtSaveZip) not found
running build_scripts
running install_lib
running install_scripts
changing mode of /usr/local/bin/apt-offline to 755
changing mode of /usr/local/bin/apt-offline-gui to 755
changing mode of /usr/local/bin/apt-offline-gui-pkexec to 755
running install_egg_info
Removing /usr/local/lib/python3.7/dist-packages/apt_offline-1.8.2.egg-info
Writing /usr/local/lib/python3.7/dist-packages/apt_offline-1.8.2.egg-info

apt-offline-gui
Traceback (most recent call last):
  File "/usr/local/bin/apt-offline-gui", line 28, in <module>
    from apt_offline_gui.AptOfflineQtMain import AptOfflineQtMain
  File "/usr/local/lib/python3.7/dist-packages/apt_offline_gui/AptOfflineQtMain.py", line 4, in <module>
    from apt_offline_gui.Ui_AptOfflineQtMain import Ui_AptOfflineMain
ModuleNotFoundError: No module named 'apt_offline_gui.Ui_AptOfflineQtMain'

**Comment by rickysarraf** [comment]
Thank you so much for the requested information. This issue is now fixed.

**Comment by KitchM** [comment]
Good to hear.  Now, if you would just tell me what to do next.........

**Comment by rickysarraf** [comment]
> Good to hear. Now, if you would just tell me what to do next.........

Your installation wasn't proper. When you install it from source, there are a bunch of PyQt files that are built, for which you need the build tools. That's what the fix is about.

Once you do the proper installation, you can follow the howto here
https://github.com/rickysarraf/apt-offline/wiki/HOWTO
