### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by KitchM** [rickysarraf/apt-offline#133]
Let me see if I understand these things correctly:
- This is a program for people who use Debian, but there is no .deb  file?
- This is a program to allow people to download packages from Debian repositories without installing them, but there is no search function?
- There is no help file or instructions?

**Comment by rickysarraf** [comment]
> Let me see if I understand these things correctly:
> 
> * This is a program for people who use Debian, but there is no .deb  file?

.deb files are part of each distribution. For example: https://packages.debian.org/search?keywords=apt-offline

> * This is a program to allow people to download packages from Debian repositories without installing them, but there is no search function?

Please elaborate more on this.

> * There is no help file or instructions?
There's the man page. It isn't integrated in the GUI but on the Linux command-line, you can read it through `man`
On the web, you can access it here: https://github.com/rickysarraf/apt-offline/wiki/HOWTO
