### ISSUE TITLE
apt wants to download archives after "apt-offline install upgrade.zip"

### ISSUE THREAD

**Issue by m-terlinde** [rickysarraf/apt-offline#134]
Hey guys,

I've done `sudo apt-offline install upgrade.zip` and `sudo apt-get upgrade`, which works well.
After that, I wanted to upgrade the kernel as well, since it won't be installed by default.

Running `sudo apt-get install linux-generic` runs into the problem, that apt wants to download more archives:
```
sudo apt-get install linux-generic
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  linux-headers-4.15.0-122 linux-headers-4.15.0-122-generic linux-headers-generic linux-image-4.15.0-122-generic linux-image-generic linux-modules-4.15.0-122-generic linux-modules-extra-4.15.0-122-generic
Suggested packages:
  fdutils linux-doc-4.15.0 | linux-source-4.15.0 linux-tools
Recommended packages:
  thermald
The following NEW packages will be installed:
  linux-headers-4.15.0-122 linux-headers-4.15.0-122-generic linux-image-4.15.0-122-generic linux-modules-4.15.0-122-generic linux-modules-extra-4.15.0-122-generic
The following packages will be upgraded:
  linux-generic linux-headers-generic linux-image-generic
3 upgraded, 5 newly installed, 0 to remove and 7 not upgraded.
Need to get 66.0 MB of archives.
After this operation, 333 MB of additional disk space will be used.
```

Shouldn't be everything there already by apt-offline?

I'm running Ubuntu 18.04 and apt-offline v1.8.1. I had this issue on two servers today.

Thanks,
Matthias

**Comment by m-terlinde** [comment]
I did it on a machine with internet and apt loaded the following packages:
````
Get:1 http://de.archive.ubuntu.com/ubuntu bionic-updates/main amd64 linux-modules-4.15.0-122-generic amd64 4.15.0-122.124 [13.1 MB]
Get:2 http://de.archive.ubuntu.com/ubuntu bionic-updates/main amd64 linux-image-4.15.0-122-generic amd64 4.15.0-122.124 [8,014 kB]
Get:3 http://de.archive.ubuntu.com/ubuntu bionic-updates/main amd64 linux-modules-extra-4.15.0-122-generic amd64 4.15.0-122.124 [32.8 MB]
Get:4 http://de.archive.ubuntu.com/ubuntu bionic-updates/main amd64 linux-generic amd64 4.15.0.122.109 [1,872 B]
Get:5 http://de.archive.ubuntu.com/ubuntu bionic-updates/main amd64 linux-image-generic amd64 4.15.0.122.109 [2,648 B]
Get:6 http://de.archive.ubuntu.com/ubuntu bionic-updates/main amd64 linux-headers-4.15.0-122 all 4.15.0-122.124 [10.9 MB]
Get:7 http://de.archive.ubuntu.com/ubuntu bionic-updates/main amd64 linux-headers-4.15.0-122-generic amd64 4.15.0-122.124 [1,105 kB]
Get:8 http://de.archive.ubuntu.com/ubuntu bionic-updates/main amd64 linux-headers-generic amd64 4.15.0.122.109 [2,544 B]
Fetched 66.0 MB in 42s (1,577 kB/s)
````

**Comment by rickysarraf** [comment]
You need to use the `--install-packages` option with the `set` command. It will generate the signature list of new packages to be installed along with their dependencies. THen you can proceed to downloading them in the `get` command.


Something like this example.

```
rrs@priyasi:~$ sudo apt-offline set /tmp/install.uris --install-packages linux-image-cloud-amd64
[sudo] password for rrs: 
Gathering installation details for package ['linux-image-cloud-amd64']
10:28 ♒ ॐ ♅ ⛢  ☺ 😄    

rrs@priyasi:~$ apt-offline get /tmp/install.uris  --bundle /tmp/install.zip

Fetching APT Data

Downloading linux-image-5.9.0-1-cloud-amd64 - 17 MiB                                                             
ERROR:  2 items: [###                           ]  10.6% of 17 MiB
Interrupted by user. Exiting!
10:28 ♒ ॐ ♅ ⛢  ☺ 😄    
```


If it doesn't work for you, please feel free to re-open this bug report.

**Comment by m-terlinde** [comment]
Ah thanks!
I totally missed that option.

Am 2. November 2020 06:00:24 MEZ schrieb Ritesh Raj Sarraf <notifications@github.com>:
>You need to use the `--install-packages` option with the `set` command.
>It will generate the signature list of new packages to be installed
>along with their dependencies. THen you can proceed to downloading them
>in the `get` command.>
>>
>>
>Something like this example.>
>>
>```>
>rrs@priyasi:~$ sudo apt-offline set /tmp/install.uris
>--install-packages linux-image-cloud-amd64>
>[sudo] password for rrs: >
>Gathering installation details for package ['linux-image-cloud-amd64']>
>10:28 ♒ ॐ ♅ ⛢  ☺ 😄    >
>>
>rrs@priyasi:~$ apt-offline get /tmp/install.uris  --bundle
>/tmp/install.zip>
>>
>Fetching APT Data>
>>
>Downloading linux-image-5.9.0-1-cloud-amd64 - 17 MiB                   
>                                         >
>ERROR:  2 items: [###                           ]  10.6% of 17 MiB>
>Interrupted by user. Exiting!>
>10:28 ♒ ॐ ♅ ⛢  ☺ 😄    >
>```>
>>
>>
>If it doesn't work for you, please feel free to re-open this bug
>report.>
>>
>-- >
>You are receiving this because you authored the thread.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/rickysarraf/apt-offline/issues/134#issuecomment-720236303

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
