### ISSUE TITLE
Support for installing from backports

### ISSUE THREAD

**Issue by jgoerzen** [rickysarraf/apt-offline#137]
Hi,

It would be great to have apt-offline have a way to do something like `apt-get install -t buster-backports foo`.

Thanks!

**Comment by rickysarraf** [comment]
Hello @jgoerzen 

`apt-offline` does have that support.

```
rrs@priyasi:~/.../gitlab (main)$ sudo apt-offline set /tmp/set.uris --install-packages gnome-todo --release buster 
Gathering installation details for package ['gnome-todo']
20:38 ♒ ॐ ♅ ♄ ⛢     ☺ 😄    

rrs@priyasi:~/.../gitlab (main)$ cat /tmp/set.uris 
'http://deb.debian.org/debian/pool/main/libp/libpeas/libpeas-common_1.28.0-2_all.deb' libpeas-common_1.28.0-2_all.deb 53208 MD5Sum:e9427362203a610e6f15b1383f9fd9a6
'http://deb.debian.org/debian/pool/main/libp/libpeas/libpeas-1.0-0_1.28.0-2+b1_amd64.deb' libpeas-1.0-0_1.28.0-2+b1_amd64.deb 65132 MD5Sum:26f1f4f06583be1c147533dfa7644b56
'http://deb.debian.org/debian/pool/main/g/gnome-todo/gnome-todo-common_3.28.1-5_all.deb' gnome-todo-common_3.28.1-5_all.deb 233800 MD5Sum:e84500636e0da8f4b125360f4681d32f
'http://deb.debian.org/debian/pool/main/g/gnome-todo/libgnome-todo_3.28.1-5+b1_amd64.deb' libgnome-todo_3.28.1-5+b1_amd64.deb 6552 MD5Sum:e3f4a72d7f7c7e6377e70bef4e55c9f2
'http://deb.debian.org/debian/pool/main/g/gnome-todo/gnome-todo_3.28.1-5+b1_amd64.deb' gnome-todo_3.28.1-5+b1_amd64.deb 151248 MD5Sum:4285d719fb3bcf51d1682e633df48912
20:38 ♒ ॐ ♅ ♄ ⛢     ☺ 😄  
```

**Comment by jgoerzen** [comment]
Ah, fantastic.  OK, that does make sense!  I am also wondering if it supports --no-install-recommends in some way.  (or how it decides whether to install the recommends).

**Comment by rickysarraf** [comment]
> Ah, fantastic. OK, that does make sense! I am also wondering if it supports --no-install-recommends in some way. (or how it decides whether to install the recommends).

No. Not from `apt-offline` as the calling program. Because `apt-offline` tries to use multiple apt backends, like: `apt, python-apt, apt-get`. So having certain callable features available through all the interfaces is a must for `apt-offline`. So for `Recommends`, I'd suggest best to have it defined in the `/etc/apt/apt.conf` config file and let that aspect be delegated to `libapt`.

**Comment by rickysarraf** [comment]
There's nothing much to do here in `apt-offline`. So closing this report.
