### ISSUE TITLE
showing errors about failed list downloads is misleading

### ISSUE THREAD

**Issue by R-Sommer** [rickysarraf/apt-offline#14]
apt-offline tries to download all available apt list formats and presents errors, if some of them are missing. However, this is not a true error, as the archive manager choose the formats he supports on his site.

**Comment by rickysarraf** [comment]
On 12/29/2014 06:32 PM, Ritesh Raj Sarraf wrote:
>
> If you have suggestions, please keep them bringing. I need to again
> spend some time and refactor apt-offline.
>
> And thank you for all your support.

Hello,

As we stand today in the git repo, does it solve all your bugs ? I am
thinking of doing a release next week or so, but wanted your feedback

-- 
Ritesh Raj Sarraf
RESEARCHUT - http://www.researchut.com
"Necessity is the mother of invention."

**Comment by R-Sommer** [comment]
Hi, apt-offline is still not working at all with my installations. You confirmed it 16 days ago "After the trusty container setup, I think I see some problem with Ubuntu. Let me investigate."

**Comment by rickysarraf** [comment]
That was fixed. That's why I closed the bug report. 


"This is fixed with commit id: cfaf52a and will be part of the next release."

**Comment by R-Sommer** [comment]
Hmm, it looks like there is some misunderstanding. apt-offline works without any error but apt has nothing to install. That means, set, get and install are running fine, but apt upgrade (also apt-get upgrade) does not update anything. I've tested this on two sites with two different mirrors.

**Comment by R-Sommer** [comment]
BTW: AptOfflineLib.py line 73 does have two tab characters instead off 16 blanks. I'm not sure if this is a display error on github only.

**Comment by R-Sommer** [comment]
I retested it with 1.6 and now everything looks fine (with apt-get upgrade. apt upgrade still wants to download new kernel packages due to the --with-new-pkgs option)

**Comment by rickysarraf** [comment]
On 01/14/2015 07:06 PM, Roland Sommer wrote:
> I retested it with 1.6 and now everything looks fine (with apt-get
> upgrade. apt upgrade still wants to download new kernel packages due
> to the --with-new-pkgs option)

I'm glad everything is working. I went ahead with the release because I
personally tested it on my box, and everything worked fine.

Again, I appreciate all the feedback you have provided.

-- 
Ritesh Raj Sarraf
RESEARCHUT - http://www.researchut.com
"Necessity is the mother of invention."

**Comment by devth** [comment]
Because of all the errors I can't actually tell if `apt-offline` was successful. It created a zip. But it didn't work on the target machine. `¯\_(ツ)_/¯ `

**Comment by rickysarraf** [comment]
On Tue, 2015-08-25 at 12:34 -0700, Trevor Hartman wrote:
> Because of all the errors I can't actually tell if apt-offline was 
> successful. It created a zip. But it didn't work on the target 
> machine. ¯\_(ツ)_/¯

I think we've fixed this with the version in the git repository.

What version are you seeing the problem on ?


-- 
Ritesh Raj Sarraf
RESEARCHUT - http://www.researchut.com
"Necessity is the mother of invention."
