### ISSUE TITLE
Generates 0-byte signature files

### ISSUE THREAD

**Issue by jgoerzen** [rickysarraf/apt-offline#141]
Hi,

This is with version 1.8.2-1~bpo10+1.

```
# apt-offline --verbose set /tmp/aptoffline3.sig --install-packages screen
Gathering installation details for package ['screen']
# ls -l /tmp/aptoffline3.sig
-rw-r--r-- 1 root root 0 Jan  6 08:00 /tmp/aptoffline3.sig
```

I had previously run it with --update and --upgrade as well.  It performed those actions but did not install the package screen.  The package screen is not installed on this system.

Thanks!

John

**Comment by rickysarraf** [comment]
Not sure what specifically is the case in your case. The only scenario when you will reach that stage is when you request for package which is already installed. And that is because `apt` doesn't treat that request as an error. But then you mentioned that `screen` was *not* installed.


```
rrs@priyasi: $ apt policy screen
screen:
  Installed: 4.8.0-3
  Candidate: 4.8.0-3
  Version table:
 *** 4.8.0-3 990
        990 http://deb.debian.org/debian testing/main amd64 Packages
        990 http://deb.debian.org/debian unstable/main amd64 Packages
        100 /var/lib/dpkg/status
     4.6.2-3 500
        500 http://ftp.debian.org/debian buster/main amd64 Packages
20:59 ♒ ॐ ♅ ♄ ⛢     ☺ 😄    

rrs@priyasi: $ no-proxy-apt install screen
Reading package lists... Done
Building dependency tree       
Reading state information... Done
screen is already the newest version (4.8.0-3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
20:59 ♒ ॐ ♅ ♄ ⛢     ☺ 😄    


rrs@priyasi: $ sudo apt-offline set /tmp/set.uris --install-packages screen
Gathering installation details for package ['screen']
21:00 ♒ ॐ ♅ ♄ ⛢     ☺ 😄    



rrs@priyasi: $ ls -lh /tmp/set.uris 
-rw-r--r-- 1 root root 0 Jan  6 21:00 /tmp/set.uris
21:00 ♒ ॐ ♅ ♄ ⛢     ☺ 😄    
```

**Comment by rickysarraf** [comment]
@jgoerzen What does `apt install screen` report back ?

**Comment by rickysarraf** [comment]
I see nothing weird in the code. Are you able to reproduce it persistently on multiple setups ? I tried to reproduce here but no success. So, it'd be nice if you could provide with clear steps to reproduce and the environment you are able to reproduce it in.

**Comment by jgoerzen** [comment]
I can reproduce it persistently on one machine and not another.  They are somewhat different, but the most obvious difference is that the one that can reproduce it persistently has no network access at all.  I will see about installing strace on it to see if it's making network calls, and also get you the info you're looking for from `apt install screen`.

**Comment by jgoerzen** [comment]
I nailed down the cause - although screen wasn't installed, its package did exist in /var/cache/apt/archives.

I do understand the desire to not re-download packages that are already in the apt cache.  This does, however, make it a little difficult to script (apt-offline get, transport file, apt-offline set, transport file, apt-offline install).  At minimum, it would be good to document this behavior in the manpage.

Thanks again!

**Comment by rickysarraf** [comment]
Thanks @jgoerzen for the quick finding.

Yes. `apt-offline` is clear on what tasks it wants to take up and what should strictly be expected from the underneath `apt` system.

I don't like the idea of adding all such special scenarios in the documentation. Instead, I have made the following changes, which would throw and error when the file is 0 byte in size, which is not the usual desired case under any of the scenarios.


```python
rrs@priyasi:~/.../apt-offline (master)$ git diff
diff --git a/apt_offline_core/AptOfflineCoreLib.py b/apt_offline_core/AptOfflineCoreLib.py
index 8c898b4..f88382f 100644
--- a/apt_offline_core/AptOfflineCoreLib.py
+++ b/apt_offline_core/AptOfflineCoreLib.py
@@ -2244,6 +2244,10 @@ def setter(args):
                     log.verbose("Writing to Changelog, pkgName: %s, pkgInstalledVersion %s\n" % (pkgName, pkgInstalledVersion))
                     sigFile.writelines("Changelog/%s/%s\n" % (pkgName, pkgInstalledVersion))
 
+        if os.path.getsize(Str_SetArg) == 0:
+            log.err("Generated signature file %s is of 0 bytes\n" % (Str_SetArg))
+            log.err("This is usually the case when the underneath apt system has no payload to download\n")
+            sys.exit(1)
 
 def main():
         '''Here we basically do the sanity checks, some validations
```

and the result.

```linux
rrs@priyasi:~/.../apt-offline (master)$ apt policy screen
screen:
  Installed: 4.8.0-3
  Candidate: 4.8.0-3
  Version table:
 *** 4.8.0-3 990
        990 http://deb.debian.org/debian testing/main amd64 Packages
        990 http://deb.debian.org/debian unstable/main amd64 Packages
        100 /var/lib/dpkg/status
     4.6.2-3 500
        500 http://ftp.debian.org/debian buster/main amd64 Packages
13:47 ♒ ॐ ♅ ♄ ⛢     ☺ 😄    

rrs@priyasi:~/.../apt-offline (master)$ sudo ./apt-offline set /tmp/set.uris --install-packages screen
Gathering installation details for package ['screen']
ERROR: Generated signature file /tmp/set.uris is of 0 bytes
ERROR: This is usually the case when the underneath apt system has no payload to download
13:47 ♒ ॐ ♅ ♄ ⛢      ☹ 😟=> 1  
```

**Comment by jgoerzen** [comment]
Thank you!

I guess I don't view this as a "special scenario."  If I read the manpage as I did, and develop scripts to support installation via transport of apt-offline signature files, my scripts would fail to do that consistently unless I do an apt-get clean first.  This is relevant information to anybody developing robust systems without consistent connectivity.

Anyhow, thank you for your work on apt-offline!  I appreciate it!
