### ISSUE TITLE
iOS support 

### ISSUE THREAD

**Issue by jau88** [rickysarraf/apt-offline#17]
Could this be ported on iOS please? There are no methods for iPhone users to disocnect (like using cellular data) I would really appreciate it.

**Comment by rickysarraf** [comment]
The software is written in Python. Hence, if iOS has support for Python, it would run there. Ofcourse, you'd need to run it from the CLI.

**Comment by rickysarraf** [comment]
Just to clarify, I'm closing it because there's not much to do, apart from checking whether iOS has Python support or not.

If your bug request was about native port to iOS, then no. I have no plans of porting it to iOS.
