### ISSUE TITLE
Two documentation requests

### ISSUE THREAD

**Issue by rountree** [rickysarraf/apt-offline#18]
First and foremost --- nice work.  I'm working with machines that are air-gapped due to security concerns and apt-offline is the most sane way I've found to make sure they remain up to date.  Well done.

Two requests:

First, I found that --install-package wouldn't work unless I had already done an --update --upgrade pass.  It's possible this was due to my own messing around with sources.list, but if it is a dependency I'd like to see that early on in the man page.

Second, libmagic changed its API without bumping the version number.  Version 5.22 (January 2, 2015) has magic_list.  Version 4.26 (August 30, 2008) does not.  And both compile to libmagic.so.1.0.0 despite the API change.  I haven't narrowed down the issue beyond that, but adding a note about magic_list might be useful.  I worked around the problem by installing the latest version in my home directory and using LD_LIBRARY_PATH to point to it.  (The OS in question is a Red Hat derivative used at LLNL and a few other US National labs like Sandia and Los Alamos.)

Happy to provide more details if that would be useful.

Best,

Barry

**Comment by rickysarraf** [comment]
Hello Barry,

Thank you for the feedback. It is always nice to see such.

On Monday 06 April 2015 10:01 AM, Barry Rountree wrote:
>
> First and foremost --- nice work. I'm working with machines that are
> air-gapped due to security concerns and apt-offline is the most sane
> way I've found to make sure they remain up to date. Well done.
>
> Two requests:
>
> First, I found that --install-package wouldn't work unless I had
> already done an --update --upgrade pass. It's possible this was due to
> my own messing around with sources.list, but if it is a dependency I'd
> like to see that early on in the man page.
>

That scenario would only occur if your Debian box was installed without
any network, i.e. just from the CD sources.

It is a dependency, and I've tried my best to document it in the man
page. Relevant section below.

       The  following  sequence  of commands will keep a machine up to
date, with the

       package lists one step ahead of the upgrade:

              apt-offline set foo.sig --upgrade --update Requests the
packages needed

              to  upgrade  the  machine,  based  on  the current package
lists. Also,

              requests the new package lists for the next update.


              apt-offline get foo.sig -d FOLDER Downloads the packages
for  upgrading

              the machine, along with the package lists for the next
time apt-offline

              set --upgrade is run.


              apt-offline install FOLDER/FILE Positions the packages for
the upgrade,

              along with new the package lists.


              apt-get upgrade Upgrades to the state of the earlier
package lists.


              NOTE:  On  a freshly installed box, that was installed
without the net‐

              work, the package database is null. In that case, you
first need to run

              apt-offline with just the --update option to ensure you
have a meaning‐

              ful package database


The NOTE: section should cover. Any suggestions to improve this wording
is welcome.

> Second, libmagic changed its API without bumping the version number.
> Version 5.22 (January 2, 2015) has magic_list. Version 4.26 (August
> 30, 2008) does not. And both compile to libmagic.so.1.0.0 despite the
> API change. I haven't narrowed down the issue beyond that, but adding
> a note about magic_list might be useful. I worked around the problem
> by installing the latest version in my home directory and using
> LD_LIBRARY_PATH to point to it. (The OS in question is a Red Hat
> derivative used at LLNL and a few other US National labs like Sandia
> and Los Alamos.)
>
> Happy to provide more details if that would be useful.
>
> Best,
>
> Barry
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rickysarraf/apt-offline/issues/18>.
>
Oh!!! That'd be broken then. We need to find an interface for the
version, and then check for it. Thanks for reporting this.

-- 
Ritesh Raj Sarraf
RESEARCHUT - http://www.researchut.com
"Necessity is the mother of invention."

**Comment by rountree** [comment]
I'll send a more complete bug report tomorrow, but the sources.list file
seems to be interfering with the install. I'm installing from a usb drive.
Does the default ubuntu sources.list need to be modified before I start the
process? If you need more details I'll be happy to provide them once I'm
back in the lab tomorrow.

**Comment by rickysarraf** [comment]
On Monday 06 April 2015 01:35 PM, Barry Rountree wrote:
> I'll send a more complete bug report tomorrow, but the sources.list file
> seems to be interfering with the install. I'm installing from a usb drive.
> Does the default ubuntu sources.list need to be modified before I
> start the
> process? If you need more details I'll be happy to provide them once I'm
> back in the lab tomorrow.

Yes. You will may run into problems if your initial installation was
through CD Disc, and its repository details are still in the
sources.list file.

Please share your sources.list file. That'll stand a good start.

-- 
Ritesh Raj Sarraf
RESEARCHUT - http://www.researchut.com
"Necessity is the mother of invention."

**Comment by rountree** [comment]
Ha!  Working now.  I reinstalled the air-gapped machine from scratch and documented everything I did.  The sources.list file seems to be fine; there wasn't a "cdrom" listing in it, so that wasn't an issue.  Taking care to do a full cycle of "update" and then a full cycle of "upgrade" worked like a charm.   Trying a "build-essential" now....

**Comment by rickysarraf** [comment]
On Tuesday 07 April 2015 04:52 PM, Barry Rountree wrote:
> Ha! Working now. I reinstalled the air-gapped machine from scratch and
> documented everything I did. The sources.list file seems to be fine;
> there wasn't a "cdrom" listing in it, so that wasn't an issue. Taking
> care to do a full cycle of "update" and then a full cycle of "upgrade"
> worked like a charm. Trying a "build-essential" now....
I'm glad it worked all well for you. :-)

Please close this bug report once you have concluded all your tests.

-- 
Ritesh Raj Sarraf
RESEARCHUT - http://www.researchut.com
"Necessity is the mother of invention."

**Comment by rickysarraf** [comment]
Closing  based on last comment.
