### ISSUE TITLE
Apt-offline fails to download large packages

### ISSUE THREAD

**Issue by SokolovMichail** [rickysarraf/apt-offline#187]
I was trying to use apt-offline to download a selection of rather large packages. But apt-offline does not complete the download properly.

The commands I am calling:
`sudo apt-offline set apt-offline/apt-offline.sig --install-packages gnupg ubuntu-desktop-minimal redis-server \
python3.8 python3-pip python3-tk ffmpeg libgtk2.0-dev pkg-config software-properties-common \
cuda-11-2 libcudnn8=8.1.1.33-1+cuda11.2 libcudnn8-dev=8.1.1.33-1+cuda11.2
`

`sudo apt-offline get apt-offline/apt-offline.sig --download-dir apt-offline/dpkg`

Attaching two log files - the output with the "--verbose" option from both of the commands. 
The machine has got internet connection - and I am able to install the packages with apt-get on the machine. 
[set.log](https://github.com/rickysarraf/apt-offline/files/8591350/set.log)
https://drive.google.com/file/d/1aj8Kr-_ptrpibSchrcF_4x_AObsfktCF/view?usp=sharing (the file is uploaded to google drive due to being 55mb in size)

**Comment by rickysarraf** [comment]
> VERBOSE: ftp://ftp.harukasan.org/ubuntu/pool/main/i/icu/libicu-dev_66.1-2ubuntu2.1_amd64.deb - 504 - [Errno -3] Temporary failure in name resolution

You do not have internet connectivity on the download machine. Next time, please share the relevant snippet in the issue description itself. I had to download 55 MiB just for this message.

**Comment by SokolovMichail** [comment]
Sorry. Next time I'll try to share the relevant snippet. I chose to provide the whole file so you could see the whole picture.
The problem is the download machine has got the needed internet connection. It has not dropped or interrupted during the download process - and it has successfully downloaded some packages.

**Comment by rickysarraf** [comment]
> Sorry. Next time I'll try to share the relevant snippet. I chose to provide the whole file so you could see the whole picture. 

No problem. 

> The problem is the download machine has got the needed internet connection. It has not dropped or interrupted during the download process - and apt-offline has successfully downloaded some packages.

Thanks for mentioning that. I just quickly skimmed through the end, given the massive log size.


```

 76 / 1309 items: [##############################] 100.0% of 2 GiB

 77 / 1309 items: [##############################] 100.0% of 2 GiB
[1;32mlibnvidia-gl-510 done                                                             
[1;0m
 77 / 1309 items: [##############################] 100.0% of 2 GiB
```

The total download size is not a problem. I use `apt-offline` with similar use cases. Here, the main problem is multifold.
For some items, like the ones from the nvidia server `https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/./libnvidia-decode-510_510.47.03-0ubuntu1_i386.deb`,  they were successfully downloaded.

Others, like `VERBOSE: ftp://ftp.harukasan.org/ubuntu/pool/main/m/mpfr4/libmpfr6_4.0.2-1_amd64.deb - 504 - [Errno -3] Temporary failure in name resolution`, have a failure, which is what `apt-offline` is reporting. 


`apt-offline` tries hard to do its best. In your case, one host (nvidia) was accessible while the other host (ftp://ftp.harukasan.org/ubuntu/) was inaccessible.

there's nothing wrong with `apt-offline` here. I'd suggest you change the Ubuntu mirror to the stock ones like `http://ftp.ubuntu.com/ubuntu` and see if that helps.

**Comment by SokolovMichail** [comment]
I tried to replace the ubuntu mirror with `http://ftp.ubuntu.com/ubuntu`(what you proposed) and I got the exact same picture- several packages did download, but the majority failed to download, despite the computer having proper internet connection and me being able to install the packages through apt-get install.
I guess that is a problem with my network, and not with the apt-offline. However, could you please tell me how does apt-offline handle downloading? wget?

**Comment by rickysarraf** [comment]
> I tried to replace the ubuntu mirror with `http://ftp.ubuntu.com/ubuntu`(what you proposed) and I got the exact same picture- several packages did download, but the majority failed to download, despite the computer having proper internet connection and me being able to install the packages through apt-get install. I guess that is a problem with my network, and not with the apt-offline. However, could you please tell me how does apt-offline handle downloading? wget?

The handling of the download is very basic. We make us of the Python Standard `urllib2` library.

https://github.com/rickysarraf/apt-offline/blob/9dff4ed97d8a7feb88714e59c4a477e7b98a11bb/apt_offline_core/AptOfflineCoreLib.py#L731-L819

**Comment by rickysarraf** [comment]
https://github.com/rickysarraf/apt-offline/blob/9dff4ed97d8a7feb88714e59c4a477e7b98a11bb/apt_offline_core/AptOfflineCoreLib.py#L750-L758

This is relevant. Per the comment, in my limited tests, `504` was mostly seen when connections were timing out. Which could happen because of slow and/or flaky network connections.

You could also consider dropping that check entirely and see what exception Python throws.

**Comment by rickysarraf** [comment]
Also, what exact version of `apt-offline` are you running ?

**Comment by SokolovMichail** [comment]
> Also, what exact version of `apt-offline` are you running ?

I am running a 1.8.2 version of apt-offline.

**Comment by SokolovMichail** [comment]
> You could also consider dropping that check entirely and see what exception Python throws.

I shall try to make the check ASAP.

**Comment by SokolovMichail** [comment]
The issue is no longer relevant. The connection on the machine I was using to download the packages is finicky indeed and is prone to timing out. 
Thank you for trying to assist me! Turns out, the issue was hardware-related.
