### ISSUE TITLE
python ./setup.py install --prefix=/foo doesn't install all of the necessary files

### ISSUE THREAD

**Issue by rountree** [rickysarraf/apt-offline#19]
Tripped over this while working on the previous issue yesterday.

Short version:  install doesn't copy over the apt_offline_core directory (and, presumably, apt_offline_gui) into the install directory specified by --prefix.  This is my first experience poking around in python's build/install system so I'm afraid I have no help to offer beyond the bug report.

Long version:

rountree@cab689 ~/local/src$ **git clone git@github.com:rickysarraf/apt-offline.git**
Cloning into 'apt-offline'...
...
rountree@cab689 ~/local/src/apt-offline$ **python --version**
Python 2.7.7
rountree@cab689 ~/local/src/apt-offline$ **python ./setup.py build --build-base=/g/g24/rountree/local/build/apt-offline install --prefix=/g/g24/rountree/local/install/apt-offline**
rountree@cab689 ~/local/src/apt-offline$ **echo $PYTHONPATH**

rountree@cab689 ~/local/src/apt-offline$ **export PYTHONPATH=/g/g24/rountree/local/install/apt-offline/**
rountree@cab689 ~/local/src/apt-offline$ **echo $PYTHONPATH**
/g/g24/rountree/local/install/apt-offline/
rountree@cab689 **~/local/src/apt-offline$ ~/local/install/apt-offline/bin/apt-offline -h**
Traceback (most recent call last):
  File "/g/g24/rountree/local/install/apt-offline/bin/apt-offline", line 25, in <module>
    from apt_offline_core.AptOfflineCoreLib import main
ImportError: No module named apt_offline_core.AptOfflineCoreLib

This fixes the the problem

rountree@cab670 ~$ **cd local/src/apt-offline/**
rountree@cab670 ~/local/src/apt-offline$ **ls**
INSTALL  Makefile  THANKS       apt-offline-gui           apt-offline-tests.sh  apt-offline.html  apt_offline_gui  release_setps
LICENSE  README    apt-offline  apt-offline-testcase.bat  apt-offline.8         apt_offline_core  bash_completion  setup.py
rountree@cab670 ~/local/src/apt-offline$ **cp -r apt_offline_core ~/local/install/apt-offline/**
rountree@cab670 ~/local/src/apt-offline$ **~/local/install/apt-offline/bin/apt-offline -h**
usage: apt-offline [-h] [--verbose] [--simulate] [-v] {set,get,install} ...
...

**Comment by rickysarraf** [comment]
On Tuesday 07 April 2015 03:45 PM, Barry Rountree wrote:
>
> Tripped over this while working on the previous issue yesterday.
>
> Short version: install doesn't copy over the apt_offline_core
> directory (and, presumably, apt_offline_gui) into the install
> directory specified by --prefix. This is my first experience poking
> around in python's build/install system so I'm afraid I have no help
> to offer beyond the bug report.
>
I tried the same here, and it worked fine for me.


rrs@learner:~/devel/apt-offline/apt-offline (master)$ python setup.py
build --build-base=/tmp/foo-apt
running build
running build_py
creating /tmp/foo-apt
creating /tmp/foo-apt/lib.linux-x86_64-2.7
creating /tmp/foo-apt/lib.linux-x86_64-2.7/apt_offline_core
copying apt_offline_core/__init__.py ->
/tmp/foo-apt/lib.linux-x86_64-2.7/apt_offline_core
copying apt_offline_core/AptOfflineCoreLib.py ->
/tmp/foo-apt/lib.linux-x86_64-2.7/apt_offline_core
copying apt_offline_core/AptOfflineDebianBtsLib.py ->
/tmp/foo-apt/lib.linux-x86_64-2.7/apt_offline_core
copying apt_offline_core/AptOfflineLib.py ->
/tmp/foo-apt/lib.linux-x86_64-2.7/apt_offline_core
copying apt_offline_core/AptOfflineMagicLib.py ->
/tmp/foo-apt/lib.linux-x86_64-2.7/apt_offline_core
copying apt_offline_core/AptOffline_argparse.py ->
/tmp/foo-apt/lib.linux-x86_64-2.7/apt_offline_core
creating /tmp/foo-apt/lib.linux-x86_64-2.7/apt_offline_gui
copying apt_offline_gui/__init__.py ->
/tmp/foo-apt/lib.linux-x86_64-2.7/apt_offline_gui
copying apt_offline_gui/AptOfflineQtAbout.py ->
/tmp/foo-apt/lib.linux-x86_64-2.7/apt_offline_gui
copying apt_offline_gui/AptOfflineQtCommon.py ->
/tmp/foo-apt/lib.linux-x86_64-2.7/apt_offline_gui
copying apt_offline_gui/AptOfflineQtCreateProfile.py ->
/tmp/foo-apt/lib.linux-x86_64-2.7/apt_offline_gui
copying apt_offline_gui/AptOfflineQtFetch.py ->
/tmp/foo-apt/lib.linux-x86_64-2.7/apt_offline_gui
copying apt_offline_gui/AptOfflineQtFetchOptions.py ->
/tmp/foo-apt/lib.linux-x86_64-2.7/apt_offline_gui
copying apt_offline_gui/AptOfflineQtInstall.py ->
/tmp/foo-apt/lib.linux-x86_64-2.7/apt_offline_gui
copying apt_offline_gui/AptOfflineQtInstallBugList.py ->
/tmp/foo-apt/lib.linux-x86_64-2.7/apt_offline_gui
copying apt_offline_gui/AptOfflineQtMain.py ->
/tmp/foo-apt/lib.linux-x86_64-2.7/apt_offline_gui
copying apt_offline_gui/AptOfflineQtSaveZip.py ->
/tmp/foo-apt/lib.linux-x86_64-2.7/apt_offline_gui
copying apt_offline_gui/QtProgressBar.py ->
/tmp/foo-apt/lib.linux-x86_64-2.7/apt_offline_gui
copying apt_offline_gui/resources_rc.py ->
/tmp/foo-apt/lib.linux-x86_64-2.7/apt_offline_gui
copying apt_offline_gui/Ui_AptOfflineQtAbout.py ->
/tmp/foo-apt/lib.linux-x86_64-2.7/apt_offline_gui
copying apt_offline_gui/Ui_AptOfflineQtCreateProfile.py ->
/tmp/foo-apt/lib.linux-x86_64-2.7/apt_offline_gui
copying apt_offline_gui/Ui_AptOfflineQtFetch.py ->
/tmp/foo-apt/lib.linux-x86_64-2.7/apt_offline_gui
copying apt_offline_gui/Ui_AptOfflineQtFetchOptions.py ->
/tmp/foo-apt/lib.linux-x86_64-2.7/apt_offline_gui
copying apt_offline_gui/Ui_AptOfflineQtInstall.py ->
/tmp/foo-apt/lib.linux-x86_64-2.7/apt_offline_gui
copying apt_offline_gui/Ui_AptOfflineQtInstallBugList.py ->
/tmp/foo-apt/lib.linux-x86_64-2.7/apt_offline_gui
copying apt_offline_gui/Ui_AptOfflineQtMain.py ->
/tmp/foo-apt/lib.linux-x86_64-2.7/apt_offline_gui
copying apt_offline_gui/Ui_AptOfflineQtSaveZip.py ->
/tmp/foo-apt/lib.linux-x86_64-2.7/apt_offline_gui
copying apt_offline_gui/UiDataStructs.py ->
/tmp/foo-apt/lib.linux-x86_64-2.7/apt_offline_gui
running build_scripts
creating /tmp/foo-apt/scripts-2.7
copying and adjusting apt-offline -> /tmp/foo-apt/scripts-2.7
copying and adjusting apt-offline-gui -> /tmp/foo-apt/scripts-2.7
changing mode of /tmp/foo-apt/scripts-2.7/apt-offline from 644 to 755
changing mode of /tmp/foo-apt/scripts-2.7/apt-offline-gui from 644 to 755
13:17 ♒♒♒   ☺   



rrs@learner:~/devel/apt-offline/apt-offline (master)$ python setup.py
install --prefix=/tmp/foo-apt-install
running install
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/apt_offline_core
copying apt_offline_core/__init__.py ->
build/lib.linux-x86_64-2.7/apt_offline_core
copying apt_offline_core/AptOfflineCoreLib.py ->
build/lib.linux-x86_64-2.7/apt_offline_core
copying apt_offline_core/AptOfflineDebianBtsLib.py ->
build/lib.linux-x86_64-2.7/apt_offline_core
copying apt_offline_core/AptOfflineLib.py ->
build/lib.linux-x86_64-2.7/apt_offline_core
copying apt_offline_core/AptOfflineMagicLib.py ->
build/lib.linux-x86_64-2.7/apt_offline_core
copying apt_offline_core/AptOffline_argparse.py ->
build/lib.linux-x86_64-2.7/apt_offline_core
creating build/lib.linux-x86_64-2.7/apt_offline_gui
copying apt_offline_gui/__init__.py ->
build/lib.linux-x86_64-2.7/apt_offline_gui
copying apt_offline_gui/AptOfflineQtAbout.py ->
build/lib.linux-x86_64-2.7/apt_offline_gui
copying apt_offline_gui/AptOfflineQtCommon.py ->
build/lib.linux-x86_64-2.7/apt_offline_gui
copying apt_offline_gui/AptOfflineQtCreateProfile.py ->
build/lib.linux-x86_64-2.7/apt_offline_gui
copying apt_offline_gui/AptOfflineQtFetch.py ->
build/lib.linux-x86_64-2.7/apt_offline_gui
copying apt_offline_gui/AptOfflineQtFetchOptions.py ->
build/lib.linux-x86_64-2.7/apt_offline_gui
copying apt_offline_gui/AptOfflineQtInstall.py ->
build/lib.linux-x86_64-2.7/apt_offline_gui
copying apt_offline_gui/AptOfflineQtInstallBugList.py ->
build/lib.linux-x86_64-2.7/apt_offline_gui
copying apt_offline_gui/AptOfflineQtMain.py ->
build/lib.linux-x86_64-2.7/apt_offline_gui
copying apt_offline_gui/AptOfflineQtSaveZip.py ->
build/lib.linux-x86_64-2.7/apt_offline_gui
copying apt_offline_gui/QtProgressBar.py ->
build/lib.linux-x86_64-2.7/apt_offline_gui
copying apt_offline_gui/resources_rc.py ->
build/lib.linux-x86_64-2.7/apt_offline_gui
copying apt_offline_gui/Ui_AptOfflineQtAbout.py ->
build/lib.linux-x86_64-2.7/apt_offline_gui
copying apt_offline_gui/Ui_AptOfflineQtCreateProfile.py ->
build/lib.linux-x86_64-2.7/apt_offline_gui
copying apt_offline_gui/Ui_AptOfflineQtFetch.py ->
build/lib.linux-x86_64-2.7/apt_offline_gui
copying apt_offline_gui/Ui_AptOfflineQtFetchOptions.py ->
build/lib.linux-x86_64-2.7/apt_offline_gui
copying apt_offline_gui/Ui_AptOfflineQtInstall.py ->
build/lib.linux-x86_64-2.7/apt_offline_gui
copying apt_offline_gui/Ui_AptOfflineQtInstallBugList.py ->
build/lib.linux-x86_64-2.7/apt_offline_gui
copying apt_offline_gui/Ui_AptOfflineQtMain.py ->
build/lib.linux-x86_64-2.7/apt_offline_gui
copying apt_offline_gui/Ui_AptOfflineQtSaveZip.py ->
build/lib.linux-x86_64-2.7/apt_offline_gui
copying apt_offline_gui/UiDataStructs.py ->
build/lib.linux-x86_64-2.7/apt_offline_gui
running build_scripts
creating build/scripts-2.7
copying and adjusting apt-offline -> build/scripts-2.7
copying and adjusting apt-offline-gui -> build/scripts-2.7
changing mode of build/scripts-2.7/apt-offline from 644 to 755
changing mode of build/scripts-2.7/apt-offline-gui from 644 to 755
running install_lib
creating /tmp/foo-apt-install
creating /tmp/foo-apt-install/lib
creating /tmp/foo-apt-install/lib/python2.7
creating /tmp/foo-apt-install/lib/python2.7/site-packages
creating /tmp/foo-apt-install/lib/python2.7/site-packages/apt_offline_core
copying build/lib.linux-x86_64-2.7/apt_offline_core/__init__.py ->
/tmp/foo-apt-install/lib/python2.7/site-packages/apt_offline_core
copying
build/lib.linux-x86_64-2.7/apt_offline_core/AptOfflineDebianBtsLib.py ->
/tmp/foo-apt-install/lib/python2.7/site-packages/apt_offline_core
copying
build/lib.linux-x86_64-2.7/apt_offline_core/AptOfflineMagicLib.py ->
/tmp/foo-apt-install/lib/python2.7/site-packages/apt_offline_core
copying build/lib.linux-x86_64-2.7/apt_offline_core/AptOfflineLib.py ->
/tmp/foo-apt-install/lib/python2.7/site-packages/apt_offline_core
copying
build/lib.linux-x86_64-2.7/apt_offline_core/AptOffline_argparse.py ->
/tmp/foo-apt-install/lib/python2.7/site-packages/apt_offline_core
copying build/lib.linux-x86_64-2.7/apt_offline_core/AptOfflineCoreLib.py
-> /tmp/foo-apt-install/lib/python2.7/site-packages/apt_offline_core
creating /tmp/foo-apt-install/lib/python2.7/site-packages/apt_offline_gui
copying build/lib.linux-x86_64-2.7/apt_offline_gui/UiDataStructs.py ->
/tmp/foo-apt-install/lib/python2.7/site-packages/apt_offline_gui
copying
build/lib.linux-x86_64-2.7/apt_offline_gui/Ui_AptOfflineQtCreateProfile.py
-> /tmp/foo-apt-install/lib/python2.7/site-packages/apt_offline_gui
copying build/lib.linux-x86_64-2.7/apt_offline_gui/AptOfflineQtFetch.py
-> /tmp/foo-apt-install/lib/python2.7/site-packages/apt_offline_gui
copying build/lib.linux-x86_64-2.7/apt_offline_gui/__init__.py ->
/tmp/foo-apt-install/lib/python2.7/site-packages/apt_offline_gui
copying
build/lib.linux-x86_64-2.7/apt_offline_gui/AptOfflineQtInstallBugList.py
-> /tmp/foo-apt-install/lib/python2.7/site-packages/apt_offline_gui
copying
build/lib.linux-x86_64-2.7/apt_offline_gui/AptOfflineQtFetchOptions.py
-> /tmp/foo-apt-install/lib/python2.7/site-packages/apt_offline_gui
copying
build/lib.linux-x86_64-2.7/apt_offline_gui/Ui_AptOfflineQtAbout.py ->
/tmp/foo-apt-install/lib/python2.7/site-packages/apt_offline_gui
copying
build/lib.linux-x86_64-2.7/apt_offline_gui/AptOfflineQtCreateProfile.py
-> /tmp/foo-apt-install/lib/python2.7/site-packages/apt_offline_gui
copying
build/lib.linux-x86_64-2.7/apt_offline_gui/Ui_AptOfflineQtFetchOptions.py ->
/tmp/foo-apt-install/lib/python2.7/site-packages/apt_offline_gui
copying build/lib.linux-x86_64-2.7/apt_offline_gui/AptOfflineQtCommon.py
-> /tmp/foo-apt-install/lib/python2.7/site-packages/apt_offline_gui
copying build/lib.linux-x86_64-2.7/apt_offline_gui/resources_rc.py ->
/tmp/foo-apt-install/lib/python2.7/site-packages/apt_offline_gui
copying
build/lib.linux-x86_64-2.7/apt_offline_gui/Ui_AptOfflineQtMain.py ->
/tmp/foo-apt-install/lib/python2.7/site-packages/apt_offline_gui
copying
build/lib.linux-x86_64-2.7/apt_offline_gui/Ui_AptOfflineQtSaveZip.py ->
/tmp/foo-apt-install/lib/python2.7/site-packages/apt_offline_gui
copying build/lib.linux-x86_64-2.7/apt_offline_gui/QtProgressBar.py ->
/tmp/foo-apt-install/lib/python2.7/site-packages/apt_offline_gui
copying
build/lib.linux-x86_64-2.7/apt_offline_gui/AptOfflineQtInstall.py ->
/tmp/foo-apt-install/lib/python2.7/site-packages/apt_offline_gui
copying
build/lib.linux-x86_64-2.7/apt_offline_gui/Ui_AptOfflineQtInstallBugList.py
-> /tmp/foo-apt-install/lib/python2.7/site-packages/apt_offline_gui
copying build/lib.linux-x86_64-2.7/apt_offline_gui/AptOfflineQtAbout.py
-> /tmp/foo-apt-install/lib/python2.7/site-packages/apt_offline_gui
copying
build/lib.linux-x86_64-2.7/apt_offline_gui/Ui_AptOfflineQtInstall.py ->
/tmp/foo-apt-install/lib/python2.7/site-packages/apt_offline_gui
copying
build/lib.linux-x86_64-2.7/apt_offline_gui/AptOfflineQtSaveZip.py ->
/tmp/foo-apt-install/lib/python2.7/site-packages/apt_offline_gui
copying
build/lib.linux-x86_64-2.7/apt_offline_gui/Ui_AptOfflineQtFetch.py ->
/tmp/foo-apt-install/lib/python2.7/site-packages/apt_offline_gui
copying build/lib.linux-x86_64-2.7/apt_offline_gui/AptOfflineQtMain.py
-> /tmp/foo-apt-install/lib/python2.7/site-packages/apt_offline_gui
byte-compiling
/tmp/foo-apt-install/lib/python2.7/site-packages/apt_offline_core/__init__.py
to __init__.pyc
byte-compiling
/tmp/foo-apt-install/lib/python2.7/site-packages/apt_offline_core/AptOfflineDebianBtsLib.py
to AptOfflineDebianBtsLib.pyc
byte-compiling
/tmp/foo-apt-install/lib/python2.7/site-packages/apt_offline_core/AptOfflineMagicLib.py
to AptOfflineMagicLib.pyc
byte-compiling
/tmp/foo-apt-install/lib/python2.7/site-packages/apt_offline_core/AptOfflineLib.py
to AptOfflineLib.pyc
byte-compiling
/tmp/foo-apt-install/lib/python2.7/site-packages/apt_offline_core/AptOffline_argparse.py
to AptOffline_argparse.pyc
byte-compiling
/tmp/foo-apt-install/lib/python2.7/site-packages/apt_offline_core/AptOfflineCoreLib.py
to AptOfflineCoreLib.pyc
byte-compiling
/tmp/foo-apt-install/lib/python2.7/site-packages/apt_offline_gui/UiDataStructs.py
to UiDataStructs.pyc
byte-compiling
/tmp/foo-apt-install/lib/python2.7/site-packages/apt_offline_gui/Ui_AptOfflineQtCreateProfile.py
to Ui_AptOfflineQtCreateProfile.pyc
byte-compiling
/tmp/foo-apt-install/lib/python2.7/site-packages/apt_offline_gui/AptOfflineQtFetch.py
to AptOfflineQtFetch.pyc
byte-compiling
/tmp/foo-apt-install/lib/python2.7/site-packages/apt_offline_gui/__init__.py
to __init__.pyc
byte-compiling
/tmp/foo-apt-install/lib/python2.7/site-packages/apt_offline_gui/AptOfflineQtInstallBugList.py
to AptOfflineQtInstallBugList.pyc
byte-compiling
/tmp/foo-apt-install/lib/python2.7/site-packages/apt_offline_gui/AptOfflineQtFetchOptions.py
to AptOfflineQtFetchOptions.pyc
byte-compiling
/tmp/foo-apt-install/lib/python2.7/site-packages/apt_offline_gui/Ui_AptOfflineQtAbout.py
to Ui_AptOfflineQtAbout.pyc
byte-compiling
/tmp/foo-apt-install/lib/python2.7/site-packages/apt_offline_gui/AptOfflineQtCreateProfile.py
to AptOfflineQtCreateProfile.pyc
byte-compiling
/tmp/foo-apt-install/lib/python2.7/site-packages/apt_offline_gui/Ui_AptOfflineQtFetchOptions.py
to Ui_AptOfflineQtFetchOptions.pyc
byte-compiling
/tmp/foo-apt-install/lib/python2.7/site-packages/apt_offline_gui/AptOfflineQtCommon.py
to AptOfflineQtCommon.pyc
byte-compiling
/tmp/foo-apt-install/lib/python2.7/site-packages/apt_offline_gui/resources_rc.py
to resources_rc.pyc
byte-compiling
/tmp/foo-apt-install/lib/python2.7/site-packages/apt_offline_gui/Ui_AptOfflineQtMain.py
to Ui_AptOfflineQtMain.pyc
byte-compiling
/tmp/foo-apt-install/lib/python2.7/site-packages/apt_offline_gui/Ui_AptOfflineQtSaveZip.py
to Ui_AptOfflineQtSaveZip.pyc
byte-compiling
/tmp/foo-apt-install/lib/python2.7/site-packages/apt_offline_gui/QtProgressBar.py
to QtProgressBar.pyc
byte-compiling
/tmp/foo-apt-install/lib/python2.7/site-packages/apt_offline_gui/AptOfflineQtInstall.py
to AptOfflineQtInstall.pyc
byte-compiling
/tmp/foo-apt-install/lib/python2.7/site-packages/apt_offline_gui/Ui_AptOfflineQtInstallBugList.py
to Ui_AptOfflineQtInstallBugList.pyc
byte-compiling
/tmp/foo-apt-install/lib/python2.7/site-packages/apt_offline_gui/AptOfflineQtAbout.py
to AptOfflineQtAbout.pyc
byte-compiling
/tmp/foo-apt-install/lib/python2.7/site-packages/apt_offline_gui/Ui_AptOfflineQtInstall.py
to Ui_AptOfflineQtInstall.pyc
byte-compiling
/tmp/foo-apt-install/lib/python2.7/site-packages/apt_offline_gui/AptOfflineQtSaveZip.py
to AptOfflineQtSaveZip.pyc
byte-compiling
/tmp/foo-apt-install/lib/python2.7/site-packages/apt_offline_gui/Ui_AptOfflineQtFetch.py
to Ui_AptOfflineQtFetch.pyc
byte-compiling
/tmp/foo-apt-install/lib/python2.7/site-packages/apt_offline_gui/AptOfflineQtMain.py
to AptOfflineQtMain.pyc
running install_scripts
creating /tmp/foo-apt-install/bin
copying build/scripts-2.7/apt-offline-gui -> /tmp/foo-apt-install/bin
copying build/scripts-2.7/apt-offline -> /tmp/foo-apt-install/bin
changing mode of /tmp/foo-apt-install/bin/apt-offline-gui to 755
changing mode of /tmp/foo-apt-install/bin/apt-offline to 755
running install_egg_info
Writing
/tmp/foo-apt-install/lib/python2.7/site-packages/apt_offline-1.5-py2.7.egg-info
13:17 ♒♒♒   ☺   


rrs@learner:~/devel/apt-offline/apt-offline (master)$ ls
/tmp/foo-apt-install/
bin/  lib/
13:17 ♒♒♒   ☺   



rrs@learner:~/devel/apt-offline/apt-offline (master)$ tree
/tmp/foo-apt-install/
/tmp/foo-apt-install/
├── bin
│   ├── apt-offline
│   └── apt-offline-gui
└── lib
    └── python2.7
        └── site-packages
            ├── apt_offline-1.5-py2.7.egg-info
            ├── apt_offline_core
            │   ├── AptOffline_argparse.py
            │   ├── AptOffline_argparse.pyc
            │   ├── AptOfflineCoreLib.py
            │   ├── AptOfflineCoreLib.pyc
            │   ├── AptOfflineDebianBtsLib.py
            │   ├── AptOfflineDebianBtsLib.pyc
            │   ├── AptOfflineLib.py
            │   ├── AptOfflineLib.pyc
            │   ├── AptOfflineMagicLib.py
            │   ├── AptOfflineMagicLib.pyc
            │   ├── __init__.py
            │   └── __init__.pyc
            └── apt_offline_gui
                ├── AptOfflineQtAbout.py
                ├── AptOfflineQtAbout.pyc
                ├── AptOfflineQtCommon.py
                ├── AptOfflineQtCommon.pyc
                ├── AptOfflineQtCreateProfile.py
                ├── AptOfflineQtCreateProfile.pyc
                ├── AptOfflineQtFetchOptions.py
                ├── AptOfflineQtFetchOptions.pyc
                ├── AptOfflineQtFetch.py
                ├── AptOfflineQtFetch.pyc
                ├── AptOfflineQtInstallBugList.py
                ├── AptOfflineQtInstallBugList.pyc
                ├── AptOfflineQtInstall.py
                ├── AptOfflineQtInstall.pyc
                ├── AptOfflineQtMain.py
                ├── AptOfflineQtMain.pyc
                ├── AptOfflineQtSaveZip.py
                ├── AptOfflineQtSaveZip.pyc
                ├── __init__.py
                ├── __init__.pyc
                ├── QtProgressBar.py
                ├── QtProgressBar.pyc
                ├── resources_rc.py
                ├── resources_rc.pyc
                ├── Ui_AptOfflineQtAbout.py
                ├── Ui_AptOfflineQtAbout.pyc
                ├── Ui_AptOfflineQtCreateProfile.py
                ├── Ui_AptOfflineQtCreateProfile.pyc
                ├── Ui_AptOfflineQtFetchOptions.py
                ├── Ui_AptOfflineQtFetchOptions.pyc
                ├── Ui_AptOfflineQtFetch.py
                ├── Ui_AptOfflineQtFetch.pyc
                ├── Ui_AptOfflineQtInstallBugList.py
                ├── Ui_AptOfflineQtInstallBugList.pyc
                ├── Ui_AptOfflineQtInstall.py
                ├── Ui_AptOfflineQtInstall.pyc
                ├── Ui_AptOfflineQtMain.py
                ├── Ui_AptOfflineQtMain.pyc
                ├── Ui_AptOfflineQtSaveZip.py
                ├── Ui_AptOfflineQtSaveZip.pyc
                ├── UiDataStructs.py
                └── UiDataStructs.pyc

6 directories, 57 files
13:18 ♒♒♒   ☺   



rrs@learner:~/devel/apt-offline/apt-offline (master)$ cd
/tmp/foo-apt-install/
13:18 ♒♒♒   ☺   

rrs@learner:/tmp/foo-apt-install$ ls
bin/  lib/
13:18 ♒♒♒   ☺   


rrs@learner:/tmp/foo-apt-install$ ./bin/apt-offline -h
usage: apt-offline [-h] [--verbose] [--simulate] [-v] {set,get,install} ...

Offline APT Package Manager - 1.6

positional arguments:
  {set,get,install}

optional arguments:
  -h, --help         show this help message and exit
  --verbose          Enable verbose messages
  --simulate         Just simulate. Very helpful when debugging
  -v, --version      show program's version number and exit

(C) 2005 - 2015 Ritesh Raj Sarraf - This program comes with ABSOLUTELY NO
WARRANTY. This is free software, and you are welcome to redistribute it
under
the GNU GPL Version 3 (or later) License
13:18 ♒♒♒   ☺   


-- 
Ritesh Raj Sarraf
RESEARCHUT - http://www.researchut.com
"Necessity is the mother of invention."

**Comment by rickysarraf** [comment]
No feedback. Hence closing.
