### ISSUE TITLE
release 1.8.5 with Python 3.10+ support

### ISSUE THREAD

**Issue by guillaume-d** [rickysarraf/apt-offline#191]
apt-offline 1.8.4 does not work on recent setups because of Python 3.10+ threading lib deprecations.
It was fixed in the main branch two months ago in https://github.com/rickysarraf/apt-offline/commit/9dff4ed97d8a7feb88714e59c4a477e7b98a11bb.
Could that be released soon to help users to get a working apt-offline? At the moment apt-offline is unusable in at least the following Linux distributions:
- Debian bookworm (current `testing`, future Debian 12): https://packages.debian.org/bookworm/apt-offline
- Ubuntu Jammy Jellyfish (22.04, current LTS :disappointed:): https://packages.ubuntu.com/jammy/apt-offline, and of course all later non-LTS Ubuntu releases

**Comment by rickysarraf** [comment]
Thank you for reporting this. I try to keep the Debian packages updated but it is possible I may have missed it in the recent months. I will look at it this week.

**Comment by guillaume-d** [comment]
Any news?
It has been two months now, would you accept a [Debian NMU](https://wiki.debian.org/NonMaintainerUpload) for this?
Maybe even a [low-threshold NMU](https://wiki.debian.org/LowThresholdNmu)?
Beware, I have never done one (I am quite familiar with deb packaging though), but I can try.
No promises though, so anyone else can still step up!

**Comment by guillaume-d** [comment]
Hum, sorry, missed the fact a new project release would be needed 1st...

I may help with that too (at least initiating a MR with 2. from https://github.com/rickysarraf/apt-offline/blob/master/release_setps seems easy enough), but eventually someone with enough credentials will have to merge and create the GitHub release.

**Comment by rickysarraf** [comment]
> Or maybe you'd prefer a new project release instead?
> 
> I may help with that too (at least initiating a MR with 2. from https://github.com/rickysarraf/apt-offline/blob/master/release_setps seems easy enough), but eventually someone with enough credentials will have to merge and create the GitHub release.
> 
> Maybe it could be 1.8.4.1 instead of 1.8.5?

Preparing a new release is the preferred way. I will try to complete it this week. 🤞🏽  Just that Real Life takes priority.

**Comment by rickysarraf** [comment]
`apt-offline` version v1.8.5 has been released. The upload to Debian has been initiated and it should reflect in the Debian repository momentarily.

Thank you for your patience @guillaume-d 🎉

**Comment by guillaume-d** [comment]
In the meantime it even landed in Ubuntu Kinetic (22.10): https://packages.ubuntu.com/kinetic/apt-offline

Thanks to _you_! Please do not apologize about delays, I did not buy any support contract! ;-)

**Comment by rickysarraf** [comment]
Upgrade your base Ubuntu to a newer release. Preferably 24.x or 26.x

Or simply install it from Debian or Ubuntu repository itself

https://archive.ubuntu.com/ubuntu/pool/universe/a/apt-offline/

s3nt fr0m a $martph0ne, excuse typ0s
