### ISSUE TITLE
Exception in thread Thread-1

### ISSUE THREAD

**Issue by Necromanus** [rickysarraf/apt-offline#196]
i've tried tried it on three machines. Every time I try to get the signature for the update in onlinepc I get this error (i.e. after typing apt-offline get update.sig --bundle update.zip):

Fetching APT Data

Downloading http://archive.ubuntu.com/ubuntu/dists/jammy/Release.gpg                                                             
http://archive.ubuntu.com/ubuntu/dists/jammy/Release.gpg done                                                             
Exception in thread Thread-1 (run):#############] 100.0% of 0 KiB
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/apt_offline_core/AptOfflineLib.py", line 691, in run
    if threading.currentThread().guiTerminateSignal:
  File "/usr/lib/python3.10/threading.py", line 1442, in currentThread
    warnings.warn('currentThread() is deprecated, use current_thread() instead',
DeprecationWarning: currentThread() is deprecated, use current_thread() instead

each tested in the current Ubuntu and Mint

**Comment by rickysarraf** [comment]
It was fixed some time back in this commit: https://github.com/rickysarraf/apt-offline/commit/9dff4ed97d8a7feb88714e59c4a477e7b98a11bb

The fixes are part of the v1.8.5 release. Please use the latest version of the package. If not available on Ubuntu, you can download the latest .deb from https://packages.debian.org/search?keywords=apt-offline
