### ISSUE TITLE
apt-offline get ... failing

### ISSUE THREAD

**Issue by DiagonalArg** [rickysarraf/apt-offline#2]
Howdy Ricky.  I'm having trouble using "apt-offline get ..." on my Ubuntu 12.04.01 machine.  The offline machine is Ubuntu 12.04.  (Both are 64 bit and apt-offline is ver. 1.1)  On my offline machine I did:

```
apt-offline set --verbose --update --install-packages pkg1 pkg2 pkg3 ... -- apt-offline.sig
```

I then followed up on my online machine:

```
apt-offline get --verbose -d <dirname> -s /var/cache/apt/archives apt-offline.sig
```

The pkg1... deb's download, but I don't get any other deb's for the update.  The total download is 19MB, which can't be on a machine that has not been updated in months.

While downloading, I get a whole lot of output with 404 errors (http://pastebin.com/04pZasYM), and at the end it gives me the errors below (below the signature). 

While I don't get any .deb's for the update, I do get a lot of files that look like (for example):

```
./download.virtualbox.org_virtualbox_debian_dists_precise_contrib_binary-amd64_Packages
./download.virtualbox.org_virtualbox_debian_dists_precise_contrib_binary-i386_Packages
./download.virtualbox.org_virtualbox_debian_dists_precise_Release
./download.virtualbox.org_virtualbox_debian_dists_precise_Release.gpg
```

Any thoughts?

/DA

ERROR: http://archive.canonical.com/ubuntu/dists/precise/partner/i18n/Index.lzma failed.
ERROR: http://security.ubuntu.com/ubuntu/dists/precise-security/main/i18n/Index.gz failed.
ERROR: http://security.ubuntu.com/ubuntu/dists/precise-security/main/i18n/Index.lzma failed.
ERROR: http://security.ubuntu.com/ubuntu/dists/precise-security/multiverse/i18n/Index.gz failed.
ERROR: http://security.ubuntu.com/ubuntu/dists/precise-security/multiverse/i18n/Index.lzma failed.
ERROR: http://security.ubuntu.com/ubuntu/dists/precise-security/restricted/i18n/Index.gz failed.
ERROR: http://security.ubuntu.com/ubuntu/dists/precise-security/restricted/i18n/Index.lzma failed.
ERROR: http://security.ubuntu.com/ubuntu/dists/precise-security/universe/i18n/Index.gz failed.
ERROR: http://security.ubuntu.com/ubuntu/dists/precise-security/universe/i18n/Index.lzma failed.
ERROR: http://us.archive.ubuntu.com/ubuntu/dists/precise/main/i18n/Index.gz failed.
ERROR: http://us.archive.ubuntu.com/ubuntu/dists/precise/main/i18n/Index.lzma failed.
ERROR: http://us.archive.ubuntu.com/ubuntu/dists/precise/multiverse/i18n/Index.gz failed.
ERROR: http://us.archive.ubuntu.com/ubuntu/dists/precise/multiverse/i18n/Index.lzma failed.
ERROR: http://us.archive.ubuntu.com/ubuntu/dists/precise/restricted/i18n/Index.gz failed.
ERROR: http://us.archive.ubuntu.com/ubuntu/dists/precise/restricted/i18n/Index.lzma failed.
ERROR: http://us.archive.ubuntu.com/ubuntu/dists/precise/universe/i18n/Index.gz failed.
ERROR: http://us.archive.ubuntu.com/ubuntu/dists/precise/universe/i18n/Index.lzma failed.
ERROR: http://us.archive.ubuntu.com/ubuntu/dists/precise-updates/main/i18n/Index.gz failed.
ERROR: http://us.archive.ubuntu.com/ubuntu/dists/precise-updates/main/i18n/Index.lzma failed.
ERROR: http://us.archive.ubuntu.com/ubuntu/dists/precise-updates/multiverse/i18n/Index.gz failed.
ERROR: http://us.archive.ubuntu.com/ubuntu/dists/precise-updates/multiverse/i18n/Index.lzma failed.
ERROR: http://us.archive.ubuntu.com/ubuntu/dists/precise-updates/restricted/i18n/Index.gz failed.
ERROR: http://us.archive.ubuntu.com/ubuntu/dists/precise-updates/restricted/i18n/Index.lzma failed.
ERROR: http://us.archive.ubuntu.com/ubuntu/dists/precise-updates/universe/i18n/Index.gz failed.
ERROR: http://us.archive.ubuntu.com/ubuntu/dists/precise-updates/universe/i18n/Index.lzma failed.
ERROR: http://us.archive.ubuntu.com/ubuntu/dists/precise-backports/main/i18n/Index.gz failed.
ERROR: http://us.archive.ubuntu.com/ubuntu/dists/precise-backports/main/i18n/Index.lzma failed.
ERROR: http://us.archive.ubuntu.com/ubuntu/dists/precise-backports/multiverse/i18n/Index.gz failed.
ERROR: http://us.archive.ubuntu.com/ubuntu/dists/precise-backports/multiverse/i18n/Index.lzma failed.
ERROR: http://us.archive.ubuntu.com/ubuntu/dists/precise-backports/restricted/i18n/Index.gz failed.
ERROR: http://us.archive.ubuntu.com/ubuntu/dists/precise-backports/restricted/i18n/Index.lzma failed.
ERROR: http://us.archive.ubuntu.com/ubuntu/dists/precise-backports/universe/i18n/Index.gz failed.
ERROR: http://us.archive.ubuntu.com/ubuntu/dists/precise-backports/universe/i18n/Index.lzma failed.

**Comment by rickysarraf** [comment]
The latest manpage cites:

```
       Sequence 1: The following set of commands, when run in sequence, will update a disconnected machine.

              apt-offline set update.sig --update

              (Generate the required data needed to update the APT database. Should be run on the disconnected machine)

              apt-offline get update.sig --bundle update.zip

              (Download the required data needed to update the APT database. Should be run on a machine with internet connectivity)

              apt-offline install update.zip

              (Installs the data needed to update the APT database. Should be run on the disconnected machine)

       Sequence  2:  With successful completion of Sequence 1, the APT database on the disconnected machine will be up-to-date. Now, the fol‐
       lowing set of commands, when run in sequence, will upgrade a disconnected machine.

              apt-offline set upgrade.sig --upgrade

              (Genereate the required data needed to upgrade the upgradable packages. Should be run on the disconnected machine)

              apt-offline get upgrade.sig --bundle upgrade.zip

              (Download the required data needed to upgrade the upgradable packages. Should be run on a machine with internet connectivity)

              apt-offline install upgrade.zip

              (Installs the data needed to upgrade the upgradable packages. Should be run on the disconnected machine)

       After successful completion of
              Sequence 1 and Sequence 2 in order, further running apt-get upgrade will result in 0 bytes of additional download.
```

which should be inline with what you last commented.

OTOH, this commit now makes the user to explicitly specify the `set` operation. 2cab46a31b65c1d4831da3b0b0ae0d7a2e4004dd


Also updated the manpage with some more minor updates.
5b8844f2a64e022a3e707c2861dbb6e12b7bccbb
