### ISSUE TITLE
Problems with large download due to HTTP error 429

### ISSUE THREAD

**Issue by misterzed88** [rickysarraf/apt-offline#213]
When doing an apt-offline get for a large download (such as for an update), the Ubuntu site may respond with error 429 (too many requests). This status is currently not handled by apt-offline and the download therefore fails with error:
"ERROR: I don't understand this error code 429"

It would be a good idea to add status code 429 to the list of retriable codes to fix this problem.

**Comment by rickysarraf** [comment]
Thank you. I'll investigate it.
