### ISSUE TITLE
Missing support for file URIs

### ISSUE THREAD

**Issue by c4bhuf** [rickysarraf/apt-offline#227]
We previously used `apt-offline get --bundle bundle.zip apt-offline.sig` to create a bundle with a .sig file that contained file URIs to locally stored deb files. 
e.g. ''file:/tmp/xcc-build/build-xcc-packages/./freeswitch-conf-vanilla_10.10.10.0%7ebookworm-1%7ebookworm%2b1_amd64.deb' freeswitch-conf-vanilla_10.10.10.0~bookworm-1~bookworm+1_amd64.deb 228088 MD5Sum:fdda61bdfd30a849d97bb3ff81fa25d5'"

This does not work anymore since version 1.8.3, where an explicit check for http, https and ftp links was added to [AptOfflineCoreLib.py](https://github.com/rickysarraf/apt-offline/blob/v1.8.3/apt_offline_core/AptOfflineCoreLib.py#L1234). Since we are on debian 12 bookworm we cannot easily downgrade to 1.8.2 (see https://packages.debian.org/search?keywords=apt-offline).

This seems to be fixed by simply adding an additional check for the file prefix.
`sed -i "s/ItemURL.startswith(('http', 'https', 'ftp'))/ItemURL.startswith(('file', 'http', 'https', 'ftp'))/g" /usr/lib/python3/dist-packages/apt_offline_core/AptOfflineCoreLib.py`

Since the fix seems in my eyes fairly simple, I would like to see support for file URIs again even though the change to check for urls was intentional (see commit https://github.com/rickysarraf/apt-offline/commit/50267a68844b70cff4c8d422df7d760a2595a65b).

**Comment by rickysarraf** [comment]
I have a PR to re-introduce it. But, out of curiosity, could you please share full verbose output of a run , where you have `file:/` URI apt repositories.

I just want a visual sense of how it behaves in the fetcher instance.

**Comment by c4brei** [comment]
Hi,

Thank you for looking into it.

I created you two logfiles:
 - [log_wo_workaround.log](https://github.com/rickysarraf/apt-offline/files/14865092/log_wo_workaround.log)  where the packages with a file uri are not added
    - `apt-offline get --bundle bundle_wo_workaround.zip /tmp/xcc-build/input/apt-offline.sig --verbose >> log_wo_workaround.log`
 - and [log_w_workaround.log](https://github.com/rickysarraf/apt-offline/files/14865086/log_w_workaround.log) with the mentioned workaround
   - `sed -i "s/ItemURL.startswith(('http', 'https', 'ftp'))/ItemURL.startswith(('file', 'http', 'https', 'ftp'))/g" /usr/lib/python3/dist-packages/apt_offline_core/AptOfflineCoreLib.py` 
   - `apt-offline get --bundle bundle_w_workaround.zip /tmp/xcc-build/input/apt-offline.sig --verbose >> log_w_workaround.log` 

Apt-Offline version is 1.8.5

**Comment by rickysarraf** [comment]
> Hi,
> 
> Thank you for looking into it.
> 
> I created you two logfiles:
> 
> * [log_wo_workaround.log](https://github.com/rickysarraf/apt-offline/files/14865092/log_wo_workaround.log)  where the packages with a file uri are not added to the .zip
>   
>   * `apt-offline get --bundle bundle_wo_workaround.zip /tmp/xcc-build/input/apt-offline.sig --verbose >> log_wo_workaround.log`
> * and [log_w_workaround.log](https://github.com/rickysarraf/apt-offline/files/14865086/log_w_workaround.log) with the mentioned workaround
>   
>   * `sed -i "s/ItemURL.startswith(('http', 'https', 'ftp'))/ItemURL.startswith(('file', 'http', 'https', 'ftp'))/g" /usr/lib/python3/dist-packages/apt_offline_core/AptOfflineCoreLib.py`
>   * `apt-offline get --bundle bundle_w_workaround.zip /tmp/xcc-build/input/apt-offline.sig --verbose >> log_w_workaround.log`
> 
> Apt-Offline version is 1.8.5

Thank you for the logs. I have merged the PR now.
