### ISSUE TITLE
Local folder cache_dir ignored

### ISSUE THREAD

**Issue by amireldor** [rickysarraf/apt-offline#25]
I am trying to download the packages on the web-enabled machine with `--cache-dir something` or `--cache-dir ./something` but it seems the directive is ignored. No files are copied to the folder once downloaded and thus there is no caching. If a download fails then all of the files would have to be downloaded again.

From some sniffing I've done in the code the cache folder is not writable when trying to cache the downloaded file. The cache directory _is_ writable when trying a simple `open()` and `write` from the main entry [point of the program. Or something like that.

Thanks!

**Comment by rickysarraf** [comment]
Here, on my box, they are copied. The catch is that the cache_dir has to be writable. Or else, it would fail.

                                                        #Add to Str_CacheDir if possible
                                                        if Str_CacheDir and os.access(Str_CacheDir, os.W_OK) == True:
                                                                try:
                                                                        shutil.copy(pkgFile, Str_CacheDir)
                                                                        log.verbose("%s copied to local cache directory %s.%s\n" % (pkgFile, Str_CacheDir, LINE_OVERWRITE_MID) )
                                                                except shutil.Error:
                                                                        log.verbose("Couldn't copy %s to %s.%s\n" % (pkgFile, Str_CacheDir, LINE_OVERWRITE_FULL) )
                                                        else:
                                                                log.verbose("cache_dir %s is not writeable. Skipping copy to it.\n" % (Str_CacheDir) )
   


So, yes, if the cache_dir is not writable, we drop it.

I'm going to close this bug report, but I don't see the bug. Please re-open if you think otherwise.

**Comment by amireldor** [comment]
Do `Sources.bz2` and translation files and the likes get copied to the cache as well? I am trying to check this issue but I don't even get past this initial stage (bad connection and stuff like that).

Moreover, (this needs a re-checked by me), while the check on the code you printed evaluated to _not-writable_, a similar check I did in the beginning of the program evaluated to _writable_ - so the program had access to the folder but somewhere while running it lost ability to write to cache.

How can I further debug this?

**Comment by rickysarraf** [comment]
On Monday 20 July 2015 01:14 PM, Amir Eldor wrote:
>
> Do |Sources.bz2| and translation files and the likes get copied to the
> cache as well? I am trying to check this issue but I don't even get
> past this initial stage (bad connection and stuff like that).
>

Your bug report was about cache dir. Which only applied to .debs.

apt-offline currently does not handle translation files.

As for Sources.[archive type], yes, it is handled.

> Moreover, (this needs a re-checked by me), while the check on the code
> you printed evaluated to /not-writable/, a similar check I did in the
> beginning of the program evaluated to /writable/ - so the program had
> access to the folder but somewhere while running it lost ability to
> write to cache.
>
> How can I further debug this?
>
--verbose ???

-- 
Ritesh Raj Sarraf
RESEARCHUT - http://www.researchut.com
"Necessity is the mother of invention."
