### ISSUE TITLE
Downloads binary .gz files as .bz2 and causes errors

### ISSUE THREAD

**Issue by gajbooks** [rickysarraf/apt-offline#40]
This downloads the Debian Jessie package list files as .bz2 instead of the proper .gz and I have to manually rename them for them to work. Only some are wrong, but it's the i386-binary, which is most of them.

**Comment by rickysarraf** [comment]
On Sat, 2015-12-12 at 13:53 -0800, gajbooks wrote:
> This downloads the Debian Jessie package files as .bz2 instead of the
> proper .gz and I have to manually rename them for them to work.

That decision, of what compression type is supported, is left to the
APT Repository administrator, of that particular mirror.

It is transparent to apt. So, as a user, you shouldn't have to worry
about that.

Can you elaborate in detail on what you are doing ? Also please provide
complete console text output.

-- 
Ritesh Raj Sarraf
RESEARCHUT - http://www.researchut.com
"Necessity is the mother of invention."

**Comment by rickysarraf** [comment]
I haven't heard back, hence closing this bug. Please feel free to re-open if you have more information.

**Comment by gajbooks** [comment]
I apparently didn't get an email notifying me of this. I haven't done
anything related to this for ages. It downloads files correctly but
force-renames them to the wrong extension which causes installation to fail
because the magic numbers are wrong for the file extension.

**Comment by rickysarraf** [comment]
Thats surprising. must have to do with github notification settings. i've reopened the bug. but please provide the information.

**Comment by rickysarraf** [comment]
@gajbooks  ^^^^^^

**Comment by gajbooks** [comment]
For each file it downloads, it shows the correct file name while it is
downloading but when it says it has completed that file it shows the same
filename but with the extension changed.

**Comment by rickysarraf** [comment]
Yes. That is working as designed. It happens if the signature generated at your box generates it for a compressor type different than what the archive support. In such cases, instead of failing, it cycles through.

I believe the output earlier was much noisy. In current git this has been improved. Is it possible for you to verify it against current git ?

**Comment by rickysarraf** [comment]
@gajbooks  I believe this issue should be fixed, and the output much less noisy, in 1.7.1 release. Please try with it and incase the bug still remains, feel free to re-open this bug report.
