### ISSUE TITLE
apt-offline install doesnt take any effect

### ISSUE THREAD

**Issue by izenk** [rickysarraf/apt-offline#41]
##### apt-offline 1.7

I have 2 vms - one offline and one online

* on offline vm: 
`apt-offline set --update --upgrade apt-offline.sig`

* on online vm:
`apt-offline get --bundle updates.zip -t 3 apt-offline.sig`

* then copy updates.zip to offline vm and:
`apt-offline install updates.zip --verbose`

* get a lot fo messages like:
VERBOSE: us.archive.ubuntu.com_ubuntu_dists_trusty is gpg clean
VERBOSE: ['security.ubuntu.com_ubuntu_dists_trusty-security', 'us.archive.ubuntu.com_ubuntu_dists_trusty-backports', 'us.archive.ubuntu.com_ubuntu_dists_trusty-updates', 'us.archive.ubuntu.com_ubuntu_dists_trusty']
security.ubuntu.com_ubuntu_dists_trusty-security_InRelease synced.
security.ubuntu.com_ubuntu_dists_trusty-security_Release synced.

* on offline vm:
`apt-get upgrade`
* and see that:

Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following package was automatically installed and is no longer required:
  libmpdec2
Use 'apt-get autoremove' to remove it.
The following packages have been kept back:
  isc-dhcp-client isc-dhcp-common linux-generic linux-headers-generic
  linux-image-generic
The following packages will be upgraded:
  accountsservice apparmor apport apt apt-transport-https apt-utils base-files
  bash-completion bind9-host bsdutils coreutils dh-python dnsutils dpkg
  e2fslibs e2fsprogs fuse gcc-4.8-base grub-common grub-pc grub-pc-bin
  grub2-common initscripts iproute iproute2 irqbalance krb5-locales
  libaccountsservice0 libapparmor-perl libapparmor1 libapt-inst1.5
  libapt-pkg4.12 libbind9-90 libblkid1 libcgmanager0 libcomerr2 libdns100
  libdrm-intel1 libdrm-radeon1 libdrm2 libexpat1 libffi6 libfreetype6 libfuse2
  libgnutls-openssl27 libgnutls26 libgssapi-krb5-2 libisc95 libisccc90
  libisccfg90 libk5crypto3 libkrb5-3 libkrb5support0 libldap-2.4-2 liblwres90
  libmount1 libnuma1 libpam-systemd libparted0debian1 libpcre3 libpng12-0
  libpolkit-agent-1-0 libpolkit-backend-1-0 libpolkit-gobject-1-0 libpython2.7
  libpython2.7-minimal libpython2.7-stdlib libpython3.4-minimal
  libpython3.4-stdlib libsqlite3-0 libss2 libssl1.0.0 libstdc++6
  libsystemd-daemon0 libsystemd-login0 libtasn1-6 libudev1 libuuid1
  libwhoopsie0 libxml2 linux-firmware linux-generic-lts-quantal
  linux-headers-generic-lts-quantal linux-image-generic-lts-quantal login lshw
  mount ntpdate openssh-client openssh-server openssh-sftp-server openssl
  parted passwd patch policykit-1 python-apport python-apt python-apt-common
  python-pkg-resources python-problem-report python-requests python-six
  python-urllib3 python2.7 python2.7-minimal python3-apport python3-apt
  python3-distupgrade python3-gdbm python3-problem-report
  python3-update-manager python3.4 python3.4-minimal rsyslog sudo
  systemd-services sysv-rc sysvinit-utils tzdata ubuntu-release-upgrader-core
  udev unzip update-manager-core util-linux uuid-runtime whoopsie
  wpasupplicant
128 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.
Need to get 53.0 MB/56.2 MB of archives.
After this operation, 19.7 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://us.archive.ubuntu.com/ubuntu/ trusty-updates/main e2fsprogs amd64 1.42.9-3ubuntu1.3 [667 kB]
Get:2 http://us.archive.ubuntu.com/ubuntu/ trusty-updates/main login amd64 1:4.1.5.1-1ubuntu9.1 [301 kB]
Get:3 http://us.archive.ubuntu.com/ubuntu/ trusty-updates/main mount amd64 2.20.1-5.1ubuntu20.7 [114 kB]
Get:4 http://us.archive.ubuntu.com/ubuntu/ trusty-updates/main tzdata all 2015g-0ubuntu0.14.04 [164 kB]
Get:5 http://us.archive.ubuntu.com/ubuntu/ trusty-updates/main sysvinit-utils amd64 2.88dsf-41ubuntu6.2 [53.1 kB]
Get:6 http://us.archive.ubuntu.com/ubuntu/ trusty-updates/main sysv-rc all 2.88dsf-41ubuntu6.2 [36.4 kB]

Can't understand what I'm doing wrong..

**Comment by rickysarraf** [comment]
On Tue, 2015-12-15 at 02:47 -0800, Ilia wrote:
> systemd-services sysv-rc sysvinit-utils tzdata ubuntu-release-
> upgrader-core
> udev unzip update-manager-core util-linux uuid-runtime whoopsie
> wpasupplicant
> 128 upgraded, 0 newly installed, 0 to remove and 5 not upgraded
> Need to get 530 MB/562 MB of archives
> After this operation, 197 MB of additional disk space will be used
> Do you want to continue? [Y/n] y
> Get:1 http://usarchiveubuntucom/ubuntu/ trusty-updates/main e2fsprogs
> amd64 1429-3ubuntu13 [667 kB]
> Get:2 http://usarchiveubuntucom/ubuntu/ trusty-updates/main login
> amd64 1:4151-1ubuntu91 [301 kB]
> Get:3 http://usarchiveubuntucom/ubuntu/ trusty-updates/main mount
> amd64 2201-51ubuntu207 [114 kB]
> Get:4 http://usarchiveubuntucom/ubuntu/ trusty-updates/main tzdata
> all 2015g-0ubuntu01404 [164 kB]
> Get:5 http://usarchiveubuntucom/ubuntu/ trusty-updates/main sysvinit-
> utils amd64 288dsf-41ubuntu62 [531 kB]
> Get:6 http://usarchiveubuntucom/ubuntu/ trusty-updates/main sysv-rc
> all 288dsf-41ubuntu62 [364 kB]
> Can't understand what I', doing wrong

There's nothing wrong here. It is working perfectly fine.

When you run `apt-offline --update --upgrade`, it picks up the APT
update database and the list of upgradable packages. So when you
installed it back, it synced all your data (apt database update + the
.debs), but now, your apt database is refreshed. So it mentions on the
new packages.

The best is to generate 2 signature files, one for --update, and
another for --upgrade. That'll help you not update the apt database
before upgrading your packages.

http://www.researchut.com/tools/apt-offline

That link and other links it references, has a good write-up. It also
has many user questions which should have answers to many of your
queries.


-- 
Ritesh Raj Sarraf
RESEARCHUT - http://www.researchut.com
"Necessity is the mother of invention."

**Comment by izenk** [comment]
Ok, got it.
Thank you
