### ISSUE TITLE
ERROR: I don't understand this error code 403

### ISSUE THREAD

**Issue by rareitmeyer** [rickysarraf/apt-offline#57]
apt-offline is producing this message when the 'get' step tries to access some files from "extra" repositories like Docker.

Snippet:
    Downloading https://apt.dockerproject.org/repo/dists/ubuntu-trusty/main/i18n/Translation-en_US.bz2                                                             
    ERROR: I don't understand this error code 403
    Please file a bug reportERROR: I don't understand this error code 403
    Please file a bug reportERROR: I don't understand this error code 403
    Please file a bug reportERROR: I don't understand this error code 403

Other requests to the same repo work fine:

    Downloading https://apt.dockerproject.org/repo/dists/ubuntu-trusty/main/binary-i386/Packages.bz2                                                             
    https://apt.dockerproject.org/repo/dists/ubuntu-trusty/main/binary-i386/Packages.bz2 done                                                             

Getting a 403 for this URL seems reasonable, as the page is indeed "forbidden" when accessed from a browser.

A potential fix might be just to add an if test and some logging code around line 850 of AptOfflineCoreLib.py, but I don't know the apt-offline code.

**Comment by rickysarraf** [comment]
Thank you for reporting this bug report. Verbose messages are not displayed by default. And 403 wasn't handled thus far. I've added it to the retriable error list. I've also changed the log facility to warn because we want the user to be aware of the error.
