### ISSUE TITLE
Update docs to clarify how (if) to use apt-offline for updates for a cd-install'd system

### ISSUE THREAD

**Issue by rareitmeyer** [rickysarraf/apt-offline#58]
Have been unsuccessful getting apt-offline to download security updates for a system installed via the debian DVDs. While the description of apt-offline makes it sound like a perfect apt-offline use case, digging through code and docs, it appears that maybe this isn't expected to work. 

All of the .sig file entries in a installed-from-DVD, never-connected system are crdom URLs, instead of web URLs, and in AptOfflineCoreLib.py there's code to skip cdrom entries (lines 1148 to 1154).

Documentation should be clearer.
- If this isn't supposed to work, documentation should spell that out so people don't spend time on it.
- If this is supposed to work, documentation should have more detail on how to do it.

**Comment by rareitmeyer** [comment]
Not sure, but perhaps the required documentation fix could be as simple as telling people to edit /etc/apt/sources.list to add two more lines:

http://ftp.us.debian.org/debian stable main contrib   # per https://www.debian.org/doc/manuals/debian-faq/ch-uptodate.en.html
deb http://security.debian.org/ jessie/updates main contrib non-free  # if running jessie, per https://www.debian.org/security/

**Comment by rickysarraf** [comment]
You mean mentioning this in the man page ?

I've thought about it before but could never come up with a concise english to add. Any such contribution will help.

In the past, I've tried to document the workflow using blog articles, but there too, I haven't really covered the apt repository aspect. We definitely should add it, both to manpages and the online articles. If you have some good english wording, please mention here.

https://www.researchut.com/tools/apt-offline
https://debian-administration.org/article/648/Offline_Package_Management_for_APT

**Comment by rickysarraf** [comment]
This is now a duplicate of https://github.com/rickysarraf/apt-offline/issues/59, which should be fixed.
