### ISSUE TITLE
1.7.2 doesn't work on Mint 17-64 Mate, and prevents 1.7 from being installed

### ISSUE THREAD

**Issue by frecor** [rickysarraf/apt-offline#61]
Attempting to install Apt-offline 1.7.2 on Linux Mint 17-64 Mate was worse than a failure for me, because it didn't work, and it prevented me from installing version 1.7 until I had reinstalled the OS. (There might be other fixes, but this was the quickest for me.) I assume it would have also prevented me from installing previous versions of Apt-offline. I tried the same thing with a live installation of Mint 17-64 Mate, and it had the same effect on it. 

I was able to install 1.7.2 on Mint 18 Mate, then 1.7, then 1.7.2, and I assume that I could have continued to do this indefinitely.  Mint 18 comes with Python 2.7.12, but I tried to install Python 2.7.13 on Mint 17 Mate (using 2.7.13's "tarball" version, which took a long time to install), and apparently succeeded, and still had the same problem with Apt-offline 1.7.2. So, I'm not sure what 1.7.2 would do to other OS's such as Windows or Mac. Earlier versions of the Windows-compatible form of Apt-offline are apparently no longer available from the official website.

**Comment by rickysarraf** [comment]
What is the problem ? **Doesn't work** does not help.

**Comment by frecor** [comment]
Sorry for not being more specific - here are the error messages:

Traceback (most recent call last):
  File "/usr/local/bin/apt-offline-gui", line 28, in <module>
    from apt_offline_gui.AptOfflineQtMain import AptOfflineQtMain
  File "/usr/local/lib/python2.7/dist-packages/apt_offline_gui/AptOfflineQtMain.py",
line 6, in <module>
    from apt_offline_gui.AptOfflineQtCreateProfile import
AptOfflineQtCreateProfile
  File "/usr/local/lib/python2.7/dist-packages/apt_offline_gui/AptOfflineQtCreateProfile.py",
line 8, in <module>
    import apt_offline_core.AptOfflineCoreLib
  File "/usr/local/lib/python2.7/dist-packages/apt_offline_core/AptOfflineCoreLib.py",
line 39, in <module>
    from ssl import SSLError, SSLEOFError
ImportError: cannot import name SSLEOFError

**Comment by rickysarraf** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

On Mon, 2017-02-13 at 13:33 -0800, frecor wrote:
> Sorry for not being more specific - here are the error messages:
> 
> Traceback (most recent call last):
> File "/usr/local/bin/apt-offline-gui", line 28, in <module>
> from apt_offline_gui.AptOfflineQtMain import AptOfflineQtMain
> File "/usr/local/lib/python2.7/dist-
> packages/apt_offline_gui/AptOfflineQtMain.py",
> line 6, in <module>
> from apt_offline_gui.AptOfflineQtCreateProfile import
> AptOfflineQtCreateProfile
> File "/usr/local/lib/python2.7/dist-
> packages/apt_offline_gui/AptOfflineQtCreateProfile.py",
> line 8, in <module>
> import apt_offline_core.AptOfflineCoreLib
> File "/usr/local/lib/python2.7/dist-
> packages/apt_offline_core/AptOfflineCoreLib.py",
> line 39, in <module>
> from ssl import SSLError, SSLEOFError
> ImportError: cannot import name SSLEOFError


Thanks for the error message. Your distribution is broken. The Python ssl module
should be provided by stock python.

rrs@learner:~/rrs-home/devel/apt-offline/apt-offline (master)$ dpkg -S
/usr/lib/python2.7/ssl.py
libpython2.7-minimal:amd64: /usr/lib/python2.7/ssl.py
2017-02-14 / 16:44:42 ♒♒♒  ☺  


- -- 
Ritesh Raj Sarraf
RESEARCHUT - http://www.researchut.com
"Necessity is the mother of invention."
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCgAdFiEEQCVDstmIVAB/Yn02pjpYo/LhdWkFAlii58sACgkQpjpYo/Lh
dWlBuw/+OmzkeSk2vwCB7PmTBME0Ss4Qmv7BDSXKm6fKdNddXNrM3dtOYVLVQyOx
B3+xzstnrYlwX8g35JatSshlHUVqDDl+OZ28CIV1Z4rafW1jKy/7BaqRWmTd6OHx
CFb88quasQ++X0UBD8Y0sIQzncAKlGcujJrr0Lfb2Sye8x/VCEJzlSt2vmGKjZOK
ft3KvpVp1z7VageHgpgEGMbPZggqHDtwHOn+eZp0MMduOB7kVU7Y6/q3bT7/c6x9
qRfswRNVa0kW6oeGKJEt7i5I1WQUaUsJ6ztz6h66qXZ6Hu0MxUgFG4Tx2OtxWu9y
B/IWQ+gvVyp45EHzBQyxy8X3+GXqv2ZXPGUoYOFTIas/vvVoLQ6Y2VYonJIzCMkS
M0ZHqMFQIFXZhPU1NN0wpKdJgX5XiYEXucKyPKYHunlEz1+ZmEa/gNOa5vYnf3lG
7Cl9yC/9MYtHjwBuIlGcVI8YvbMtNa8oA/mRK4VGTcCeH5OugHcDPGqpAdq8LaP3
BUGZ9mA+zTvYCzrCMma7wyb/Y2wcd8LaqEmyTPNOhp3v61zPKxaUJWq8paJfjbt5
+2whPT/uwSA5XmJ1lN2p75aKqaa4r5hwAurPOFMDr8lm69bnErAAEZoE2JGXwX7i
HUeT/whLldDJ7V8CN6xfWxyFZ3qBog49NHHhvEWijSkzNrq5lLg=
=TJ+n
-----END PGP SIGNATURE-----

**Comment by frecor** [comment]
I was able to install version 1.7. Does it require the ssl module?

**Comment by rickysarraf** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

On Wed, 2017-02-15 at 08:01 -0800, frecor wrote:
> I was able to install version 1.7. Does it require the ssl module?

No. The dependency on ssl module was added after the 1.7 release. If 1.7 works
for you, you can continue using it. But I'd still suggest you fix your python
installation.

- -- 
Ritesh Raj Sarraf
RESEARCHUT - http://www.researchut.com
"Necessity is the mother of invention."
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCgAdFiEEQCVDstmIVAB/Yn02pjpYo/LhdWkFAlikhvgACgkQpjpYo/Lh
dWknfhAAnnPW3BQCtBRStry3e/fBHf7ZL09jzWlD+fIbyZO83mFN1zuK+nCCMyW5
4JW67Hcf2a282rwLFFmg3U5fV1QdIbMiat9aj6sIO9A5kL/gXfqyPBPOnCO12r6v
Rox7nGC8vy6HgVsDsia/7dUDxd2AOKH7ok4ir/KyB6i95BXJi1mLifEQoh6GEL/R
bena7URm/cRdSu2wL3/qUVT8iIXh0gyyI7V4pTvuTCsyoxxM6bZpU+Cn9LDvt8SK
lrV8oidNFVQcFwpC+nrRQSulSSaBVOUwcYr17fCUiAyHzeqqKRDfmLzifO1utuR9
LjL2hAmURRK9AvPAFHhNewZv4p590mSX0UTc7Qv+dKsId+I76P5BLZeW11phVxbW
EpKjt29nPoagcxi2B7XjOsf1cajD6X+kCGRLjDKNuy7MduswkZniSS465q6Ar8Vl
tr+7wP7siUFnpA8/q5FEWraIVf86ny13qL8v1qDY4C3WlM11ERM0e0a3KxuFZ7QB
PHxtc5S/kn17l1DgDyQpP3v47j1KXmV/VlFa1CXdDxF+RW3jmCFj15KmlixkrC/B
9MaomSeA/KVKtqDnLWI7njWocEfGwI2KvN397fhW1Rt54kI74dOBQQJojoD9BjVb
JCIkAtcqFF6fItH024XFEigP+XvFZziv8FgyC0XSJk2UOvyR0UY=
=Lrjt
-----END PGP SIGNATURE-----

**Comment by rickysarraf** [comment]
I'm marking this bug closed because it is not a problem in apt-offline. Once you fix your Python installation, you should be able to use 1.7.2 also.

**Comment by rickysarraf** [comment]
I must also mention that in the trace you shared, the executed python is not the system installed one. This could be the root of your problem.

```
Traceback (most recent call last):
  File "/usr/local/bin/apt-offline-gui", line 28, in <module>
    from apt_offline_gui.AptOfflineQtMain import AptOfflineQtMain
  File "/usr/local/lib/python2.7/dist-packages/apt_offline_gui/AptOfflineQtMain.py",
line 6, in <module>
    from apt_offline_gui.AptOfflineQtCreateProfile import
AptOfflineQtCreateProfile
  File "/usr/local/lib/python2.7/dist-packages/apt_offline_gui/AptOfflineQtCreateProfile.py",
line 8, in <module>
    import apt_offline_core.AptOfflineCoreLib
  File "/usr/local/lib/python2.7/dist-packages/apt_offline_core/AptOfflineCoreLib.py",
line 39, in <module>
    from ssl import SSLError, SSLEOFError
ImportError: cannot import name SSLEOFError
```
