### ISSUE TITLE
Add --greedy option for get

### ISSUE THREAD

**Issue by crazycodr** [rickysarraf/apt-offline#71]
Related to https://serverfault.com/questions/868159/updating-an-offline-ubuntu-server.

We would benefit from being able to generate a package that includes everything that the signature specifies not just what seems to be out of date because sometimes we don't have access to the signature or the generated signature might not necessarily be the real signature of the machine at the other end. 

A --greedy or any other similar switch name would be much appreciated.

**Comment by rickysarraf** [comment]
You want a dummy package with all the dependencies added to it ?
Or do you want a .deb package instead of a .zip file ?

**Comment by crazycodr** [comment]
If you read the stackoverflow post it will provide more information about our problem but let me re-summarize it here.

- We create appliance servers that are mostly offline or have extremely poor connectivity
- We do not have the signature of the packages that were installed because, for various reasons, we don't have access to the machines to install apt-offline or we don't have a good enough connectivity to have access to them
- We can create another appliance that looks just like the one issued but with the same package list but updated to the latest
- We would want to leverage apt instead of DPKG because it becomes hell to manage order the depenendency installation
- We would like to use apt-offline to generate a complete update package from a signature such as a reproduced applicance but get extra greedy and actually take in ALL packages that we need for the update instead of just what is necessary.
- By generating a signature from another server, we'd be able to package all the required packages to their latest form and benefit from apt/apt-offline for delivery

**Comment by crazycodr** [comment]
Note that we have found a manual solution that works but requires a lot of testing to ensure it works. Using an already established tool like yours would make it much easier:

https://github.com/rickysarraf/apt-offline/issues/72

**Comment by rickysarraf** [comment]
These all look similar: #72 #71 and #75 
The approach you mention, unless the setup is identical, wouldn't be deterministic.

From what I understand, what users are seeking for is, for example to run something like the below, say on a foreign (Windows?) platform:
`apt-offline --distribution wheezy --install-packages foo-package` be run successfully, without the round-trip of signature generation

**Comment by crazycodr** [comment]
i wasn't aware of those flags... So if i understand you right, i could list all packages my app need such as mysql-client, apt-offline, jq, bc, etc and do this?

```bash
apt-offline get --output /tmp/appliance101.zip --distribution xenial --install-packages mysql-client jq python aws-cli bc
```

**Comment by rickysarraf** [comment]
No.

First, on the disconnected machine:
`apt-offline set /tmp/install-packages.txt --install-packages mysql bash emacs`

And then, on the connected machine:
`apt-offline get /tmp/install-packages.txt`

**Comment by crazycodr** [comment]
We don't have access to the disconnected machine! Let's just close this, you don't understand my request!
