### ISSUE TITLE
Add --install-packages to "get" command

### ISSUE THREAD

**Issue by crazycodr** [rickysarraf/apt-offline#72]
Related to https://serverfault.com/questions/868159/updating-an-offline-ubuntu-server.

If we want to install additional packages later and can't actually update the signature or re-run a signature buildup then we are stuck and can't install additional packages until we make a second roundtrip which is bad for appliances like ours.

It would be nice to be able to specify additional packages to install in `apt-offline get` and not just in the `set` command. Right now, there is no way to do this at all.

Another approach would be to allow updating signature files using a new `update` command or allow `set` to supplement stuff to a signature-file that has --update used on it.

**Comment by rickysarraf** [comment]
I don't see that as achievable. And that is not how the APT package manager works.
There's repo data that is centralized and mirrored throughout the globe.
Each installation of Debian is different than others, in that users choose very different sets of packages.

apt-offline generates signatures on your local machine against the repo data that is available on that machine.
Generating additional package list in the `get` operation would mean fetching the package manager's intelligence from the web, without the base install.

I don't see this possible without a round trip..

I am closing this report but if you have ways to solve this, please feel free to re-open.

**Comment by crazycodr** [comment]
Hi Ricky,

Thanks for the response. Because we didn't get a response, we had to go to a different solution and approach and ended up packaging the debs ourselves and creating a local repository that superseeds everything. From that, using apt install with fixed versions solved our problem.

Good luck
