### ISSUE TITLE
Is this behaviour normal ?

### ISSUE THREAD

**Issue by iphilhappy** [rickysarraf/apt-offline#78]
Hi,
First I would like to thank for the apt-offline module, which really eases package deployment on an offline system. It was working fine until recently. 
When I use apt-offline to do an update, I have the following ERRORS  at the end of the download:

ERROR: The following files failed to be downloaded.
ERROR: Not all errors are fatal. For eg. Translation files are not present on all mirrors.
ERROR: http://security.debian.org/dists/jessie/updates/main/i18n/Translation-en_US.lzma failed.
ERROR: http://security.debian.org/dists/jessie/updates/non-free/i18n/Translation-en_US.lzma failed.
ERROR: http://cdn-fastly.deb.debian.org/debian/dists/jessie/main/i18n/Translation-en_US.lzma failed.
ERROR: http://cdn-fastly.deb.debian.org/debian/dists/jessie/non-free/i18n/Translation-en_US.lzma failed.
ERROR: http://cdn-fastly.deb.debian.org/debian/dists/jessie/InRelease.lzma failed.
ERROR: http://cdn-fastly.deb.debian.org/debian/dists/jessie-updates/main/i18n/Translation-en_US.lzma failed.
ERROR: http://cdn-fastly.deb.debian.org/debian/dists/jessie-updates/non-free/i18n/Translation-en_US.lzma failed.
ERROR: http://cdn-fastly.deb.debian.org/debian/dists/jessie-backports/main/i18n/Translation-en_US.lzma failed.

Later on when I try to upgrade or install new package, when I run apt-get upgrade or apt-get install, the offline system tries to contact the repository for several missing packages, which is not working because this is the offline system. 

I come to the conclusion that the following error is causing my trouble:
ERROR: http://cdn-fastly.deb.debian.org/debian/dists/jessie/InRelease.lzma failed.

I don't know how to fix it. Can I have your help ?

Thanks in advance,
Philippe

**Comment by iphilhappy** [comment]
Hello,
After having installed the dowloaded items, the offline system took a while come to a stable situation and stop complaining about missing packages.
The issue is gone with time.

**Comment by rickysarraf** [comment]
For whatever reasons on the remote server that you were trying to download the files from, the `InRelease.lzma` file was missing. That file is important and that is why you were seeing those errors.

Eventually, as you mention, that file must have been made available.
