### ISSUE TITLE
routine test  - issue in installer

### ISSUE THREAD

**Issue by rickysarraf** [rickysarraf/apt-offline#8]
Installing src package file eclipse_3.8.1-5.1.dsc to /tmp/apt-offline-src-downloads-30543.
Installing src package file emacs-defaults_45.0.dsc to /tmp/apt-offline-src-downloads-30543.
Installing src package file emacs-defaults_45.0.tar.gz to /tmp/apt-offline-src-downloads-30543.
Hola!!
ERROR: I couldn't understand file type eclipse_3.8.1-5.1.debian.tar.xz.
Another Hola!!!
Hola!!
/tmp/apt-package-target-path-30543/libharfbuzz0b_0.9.28-2_amd64.deb file synced.
VERBOSE: /tmp/apt-package-target-path-30543/libharfbuzz0b_0.9.28-2_amd64.deb file synced to /tmp/apt-update-target-path-30543.
Another Hola!!!
Hola!!
/tmp/apt-package-target-path-30543/libharfbuzz-gobject0_0.9.28-2_amd64.deb file synced.
VERBOSE: /tmp/apt-package-target-path-30543/libharfbuzz-gobject0_0.9.28-2_amd64.deb file synced to /tmp/apt-update-target-path-30543.
Another Hola!!!
Hola!!
/tmp/apt-package-target-path-30543/libwayland-client0_1.5.0-1_amd64.deb file synced.
VERBOSE: /tmp/apt-package-target-path-30543/libwayland-client0_1.5.0-1_amd64.deb file synced to /tmp/apt-update-target-path-30543.
Another Hola!!!
Hola!!
/tmp/apt-package-target-path-30543/libwayland-cursor0_1.5.0-1_amd64.deb file synced.
VERBOSE: /tmp/apt-package-target-path-30543/libwayland-cursor0_1.5.0-1_amd64.deb file synced to /tmp/apt-update-target-path-30543.
Another Hola!!!
Hola!!
/tmp/apt-package-target-path-30543/libxshmfence1_1.1-3_i386.deb file synced.
VERBOSE: /tmp/apt-package-target-path-30543/libxshmfence1_1.1-3_i386.deb file synced to /tmp/apt-update-target-path-30543.
Another Hola!!!
Hola!!
/tmp/apt-package-target-path-30543/libwayland-server0_1.5.0-1_amd64.deb file synced.
VERBOSE: /tmp/apt-package-target-path-30543/libwayland-server0_1.5.0-1_amd64.deb file synced to /tmp/apt-update-target-path-30543.
Another Hola!!!
Hola!!
/tmp/apt-package-target-path-30543/texinfo_5.2.0.dfsg.1-3_amd64.deb file synced.
VERBOSE: /tmp/apt-package-target-path-30543/texinfo_5.2.0.dfsg.1-3_amd64.deb file synced to /tmp/apt-update-target-path-30543.
Another Hola!!!
Hola!!
ERROR: I couldn't understand file type eclipse_3.8.1.orig.tar.xz.
Another Hola!!!
ERROR: Disabling apt gpg check can risk your machine to compromise.

**Comment by rickysarraf** [comment]
This still needs to be investigated because xz-utils claims to suppot both, .xz and .lzma
But I'm assuming they are dealt differently.

Also, in recent conversations in debian-devel, there were talks about merits/demerits of .xz

**Comment by copyninja** [comment]
What is the issue here?. May be a proper description of bug and what was expected might help people who want to provide patch. :-)

**Comment by rickysarraf** [comment]
The issue is with the .xz extension files. I think this might have been fixed in the current git version

ERROR: I couldn't understand file type eclipse_3.8.1.orig.tar.xz

**Comment by rickysarraf** [comment]
Yes. It should be fixed. Re-open it if that is not the case.
