### ISSUE TITLE
LZMAError: Corrupt input data

### ISSUE THREAD

**Issue by david-wm-sanders** [rickysarraf/apt-offline#80]
![us_16_04_3_offline-2018-02-12-18-02-40](https://user-images.githubusercontent.com/673925/36111817-53afbc68-101f-11e8-95b0-d68f97c9f9d5.png)

Hi,

I get the above when I try to run apt-offline install on a folder of packages created with the -d option on get. A similar decompression error appears if I try to install from a bundle ZIP as well.

**Comment by rickysarraf** [comment]
It seems that either the get operation fetched corrupt data or else the
lzma support on your box is broken.

To be sure of this, I'd like to reproduce the problem on my setup. Can you
share your .sig file? The one that you created in the set operation.

s3nt fr0m a $martph0ne, excuse typ0s

**Comment by david-wm-sanders** [comment]
[update.zip](https://github.com/rickysarraf/apt-offline/files/1717394/update.zip)

Seems that GitHub throws a fit for .sig files ("not supported" yada yada") so here it is inside a ZIP archive.

**Comment by david-wm-sanders** [comment]
I think I am going to try with a different USB stick tomorrow when I can get one - just to rule out that it isn't something wrong with the stick itself.

**Comment by david-wm-sanders** [comment]
For context, I am just experimenting with apt-offline in virtualised environments at the moment to get to grips with it before using it on a real offline machine. I have two VMs, both running Ubuntu Server 16.04.3, where one was installed with an internet connection and the other without. Although I updated the online one initially, I also tried reverting it back to the fresh install snapshot and rerunning the apt-offline steps to check that something LZMA related hadn't been updated and caused this issue - to no avail unfortunately.

**Comment by david-wm-sanders** [comment]
Closing this issue as it did seem to be something on my end - either the USB was on the blink or the online machine I was using to download the packages to the bundles was corrupting them. In the end, I got it to work by using apt-offline get from PowerShell on Windows - this created a non-corrupted bundle which then installed successfully on the offline machine.

Sorry for wasting your time :)

**Comment by rickysarraf** [comment]
I've never used it on windows powershell. I'm glad it worked there too
