### ISSUE TITLE
"cannot import name SSLEOFError" on Ubuntu 14

### ISSUE THREAD

**Issue by nmgeek** [rickysarraf/apt-offline#82]
I already have a solution to this.  I am posting for posterity because I found nothing useful in a google search.

It looks to me like SSLEOFError is a symbol in the ssl module which is in the same package as the python interpreter.  It appears that the version of Python which installs on the last release of Ubuntu 14 (Python 2.7.6 ) does not include the symbol.

My solution was to back up to version 1.6.1 of apt-offline which is before the reference to SSLEOFError was introduced.

**Comment by rickysarraf** [comment]
That is very odd. SSLEOFError comes from the basic `ssl` module. It would be highly odd that Ubuntu wouldn't be shipping it. But anyways, I don't see what we can do here.

**Comment by nmgeek** [comment]
Right.  Since there is a workaround I'd close this issue.  (I just wanted this issue "on the books" so people could find the workaround when they search for the error message.)
