### ISSUE TITLE
"FATAL: Something is wrong with the apt system." before apt-get update on fresh install of Ubuntu 14

### ISSUE THREAD

**Issue by nmgeek** [rickysarraf/apt-offline#83]
I am trying to use "apt-offline set" to create a bulletproof offline installer to run on Ubuntu 14.  I get the
"FATAL: Something is wrong with the apt system." if I run "apt-offline set" before running "apt-get update".  But the point is to capture the state of the system _before_ updating the apt database so the .sig file includes all the apt database updates I would need.

I have version 1.3 of apt-offline which is the version in the Ubuntu 14 package repositories.

I built a debian package for 1.6.1 of apt-offline (which seems to the the last version which will run on Ubuntu 14).  I plan to test version 1.6.1 to see if this bug is fixed.

**Comment by nmgeek** [comment]
After some testing I can see that, if you ask for a package which is not in the apt database, you get this misleading error message:

```
$ sudo apt-offline set test.sig --update --install-packages unknown-package-name
Generating database of files that are needed for an update.
Generating database of package unknown-package-name,  and its dependencies.
E: Unable to locate package unknown-package-name
ERROR: FATAL: Something is wrong with the apt system.
```

I don't believe there is anything "wrong with the apt system."  How would I know for-sure if something is wrong with apt?

**Comment by nmgeek** [comment]
In addition to the misleading 'something is wrong" error message I believe my issue comes from lack of documentation.  Before you can attempt to install just about any package on a server with a fresh install of Ubuntu you have to update the apt database.

So you need to go through two rounds of generating signature files and transferring bundles to the offline server.  The first round accomplishes the apt database update.  Once the database is up to date apt-offline will no longer complain that the apt system is "wrong."  In the second round you can ask for any legitimate package to be installed without getting errors.

**Comment by rickysarraf** [comment]
In the 2nd comment, the error that apt produces, is presented as is to the user. Which is explanatory enough about what the error is. The 2nd error is from apt-offline. Of course we could improve on it. But I don't recollect if apt gives nice error codes.

**Comment by rickysarraf** [comment]
I've tried to improve/extend the documentation. And am always open to improvements. If you think it can be improved, can you please care to submit a patch ? Thanks.

**Comment by nmgeek** [comment]
I think the last error message should say something to the effect of "apt-offline exiting without creating signature file due to error(s ) returned by apt-get".  And the line before that should attribute the error to a specific apt command/utility.  Like,

> Error from apt-get: Unable to locate package unknown-package-name

These errors are not caused by "something wrong with the apt system."   They are caused by something wrong with the arguments provided to apt-offline, i.e. user's error.

Regarding the recommendation to document the two-phase update-then-upgrade approach after a fresh OS install I guess that would go in the man page EXAMPLES section?

**Comment by rickysarraf** [comment]
On Sun, 2018-03-11 at 15:59 +0000, nmgeek wrote:
> I think the last error message should say something to the effect of
> "apt-offline exiting without creating signature file due to error(s )
> returned by apt-get".  And the line before that should attribute the
> error to a specific apt command/utility.  Like,
> 
> > Error from apt-get: Unable to locate package unknown-package-name
> 
> These errors are not caused by "something wrong with the apt
> system."   They are caused by something wrong with the arguments
> provided to apt-offline, i.e. user's error.

Okay. Let me see what best can be done. I did not want to do guess
work, so simply left it as a generic error string. But I think what you
are asking makes more sense.

> Regarding the recommendation to document the two-phase update-then-
> upgrade approach after a fresh OS install I guess that would go in
> the man page EXAMPLES section?

Yes, Please.

-- 
Ritesh Raj Sarraf
RESEARCHUT - http://www.researchut.com
"Necessity is the mother of invention."

**Comment by rickysarraf** [comment]
The 2nd part is a doc update thing, which is fine. But please feel free to submit any PR to improve it.
