### ISSUE TITLE
Option to use particular sources.list

### ISSUE THREAD

**Issue by jdugge** [rickysarraf/apt-offline#84]
When using apt-offline in a script to automatically update an offline system, it would be helpful to use a different `sources.list` than the default.

For example, this would make it possible to only install security updates, by first generating a new `sources.list` containing only the security repositories (as suggested at https://serverfault.com/a/282518) and then calling `apt-offline --sources-list /etc/apt/security.sources.list set security_updates.ini`.

(Thanks for this package, by the way, it's a real life-saver!)

**Comment by rickysarraf** [comment]
Thanks for the bug report. This is a specific use case and a nice one to have. But I have other high priority tasks to fix currently, like a security issue https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=871656

So this'll have to wait for some time.

**Comment by jdugge** [comment]
Sure, I completely understand. Thanks for the fast reply!

**Comment by rickysarraf** [comment]
From the tool's point of view, I want to keep it clean. As in, there are some aspect of information generation which apt-offline strictly delegates to the apt subsystem. Signature generation is one of that. Signature generation involves a lot of work, primarily dependency management, which is what `apt` is the key there.

**Comment by rickysarraf** [comment]
As for this bug report, I think the use case should be easily achievable with the `--release` option in `apt-offline`, wherein you pass `--release stable-security` as the option.
