### ISSUE TITLE
Failed offline update following fresh install

### ISSUE THREAD

**Issue by Gaudeamos** [rickysarraf/apt-offline#89]
Hi Ricky

I'm trying to do an entirely offline setup-update-upgrade-install sequence using apt-offline.

I was not able to perform a successful update. There were many "404-file not found" errors during the online get step. I have seen your assurances that these errors are entirely expected and harmless, so I proceeded. 

Following the offline upgrade (30 packages upgraded) I connected the offline computer to the internet and performed an update and upgrade in the usual online manner. These steps should be entirely redundant, right? However, this update triggered an additional 349 package upgrades!

I've detailed my procedure below, with output redirected to attached files. 

The summarized procedure:

1. Offline computer: Install Linux Mint 18.3 Cinnamon from live medium
2. Offline computer: Install apt-offline
3. Offline computer: apt-offline set --update...
4. Online computer: Install apt-offline
5. Online computer: apt-offline get...
6. Offline computer: apt-offline install...
   (apt-get update is not required, right? 
   ...I've done it on previous trials with the same result)
7. Offline computer: apt-offline set upgrade...
8. Online computer: apt-offline get...
9. Offline computer: apt-offline install...
10. Offline computer: apt-get upgrade
11. Offline computer: connect to internet
12. Offline (now connected) computer: apt-get update
13. Offline (now connected) computer: apt-get upgrade

The detailed procedure:

Sorry, the formatting features are just not working for me. I've attached this in a plain text file. 
The procedure is expressed as pseudo-bash code, and characters like '#', '*', and '\' are taking on a life of their own on this post.

attachment:
[Ricky_2.txt](https://github.com/rickysarraf/apt-offline/files/2281555/Ricky_2.txt)

attachment: 
[apt-offline-failed-upgrade.tar.gz](https://github.com/rickysarraf/apt-offline/files/2280916/apt-offline-failed-upgrade.tar.gz)

**Comment by rickysarraf** [comment]
With the `-d` or `--download-dir` option, there was a bug that I fixed yesterday. Can you retry with the latest `HEAD` in the `master` branch ?

**Comment by rickysarraf** [comment]
No update from reported. Closing the issue. Please feel free to re-open if you have updated information.
