### ISSUE TITLE
Upgrade from 16.04 to 18.04

### ISSUE THREAD

**Issue by brendan77222** [rickysarraf/apt-offline#97]
I was told that I could use this to complete an upgrade from 16.04 to 18.04 offline without losing my settings, configurations, installed programs, etc. I am relatively new to Linux, but understand how to read and use man pages to accomplish a majority of things as I learn. I completed an apt-offline update and upgrade successfuly, but can't seem to get the dist-upgrade functionality to work. It always seems to call to the net no matter how I use apt-offline + apt-get. Was I misinformed on the functionality or am I misusing dist-upgrade?

If this isn't a current function, I would like to put in a formal request to add this to the wish list.

**Comment by rickysarraf** [comment]
Please follow HOWTO here: https://github.com/rickysarraf/apt-offline/wiki/HOWTO

Then give me details, along with console output, of what you ran of the commands mentioned in the HOWTO.

**Comment by rickysarraf** [comment]
Closing issue. Re-open if new information is available.
